# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── access_control ──────────────────────────────────────────────────────────
AccessControlId = Literal[True]

# ── run_event ───────────────────────────────────────────────────────────────
RunEventEvent = Literal['start', 'end']
RunEventRunType = Literal['panel', 'simulation']
RunEventMode = Literal['panel', 'product', 'policy']
RunEventStatus = Literal['started', 'ok', 'failed']

# ── subscription ────────────────────────────────────────────────────────────
SubscriptionPlan = Literal['free', 'paid']
SubscriptionStatus = Literal['active', 'cancelled']

# ── waitlist_request ────────────────────────────────────────────────────────
WaitlistRequestStatus = Literal['pending', 'invited']
