# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── api_agent_entry ─────────────────────────────────────────────────────────
ApiAgentEntryBudgetTier = Literal['tight', 'moderate', 'loose']

# ── api_persona_list_entry ──────────────────────────────────────────────────
ApiPersonaListEntryLevel = Literal['library']

# ── api_segment ─────────────────────────────────────────────────────────────
ApiSegmentKind = Literal['who', 'thinks']
