# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── room_seat ───────────────────────────────────────────────────────────────
Stance = Literal['support', 'neutral', 'concerned', 'oppose', 'resist']
BudgetTier = Literal['tight', 'moderate', 'loose']
