# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── persona ─────────────────────────────────────────────────────────────────
SourceEntityType = Literal['library_persona']
Gender = Literal['Female', 'Male']
Province = Literal['Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape']
Education = Literal['Less than primary completed', 'No schooling', 'Other', 'Primary', 'Primary completed', 'Secondary completed', 'Secondary not completed', 'Tertiary']
Occupation = Literal['Clerks', 'Clerks (informal)', 'Craft and related trades workers', 'Craft and related trades workers (informal)', 'Discouraged job seeker', 'Domestic workers (informal)', 'Elementary Occupation', 'Elementary Occupation (informal)', 'Employed', 'Learner (School)', 'Learner (TVET college)', 'Legislators; senior officials and managers', 'Legislators; senior officials and managers (informal)', 'Other not economically active', 'Plant and machine operators and assemblers', 'Plant and machine operators and assemblers (informal)', 'Professionals', 'School teacher', 'Service workers and shop and market sales workers', 'Service workers and shop and market sales workers (informal)', 'Skilled agricultural and fishery workers', 'Skilled agricultural and fishery workers (informal)', 'Technical and associate professionals', 'Technical and associate professionals (informal)', 'Unemployed', 'Unspecified']
EmploymentStatus = Literal['Discouraged job seeker', 'Employed', 'Other not economically active', 'Unemployed']
Industry = Literal['Agriculture; hunting; forestry and fishing', 'Community; social and personal services', 'Construction', 'Financial intermediation; insurance; real estate and business services', 'Manufacturing', 'Mining and quarrying', 'Private households', 'Transport; storage and communication', 'Wholesale and retail trade']
MarriageStatus = Literal['Divorced', 'Divorced or separated', 'Legally married', 'Living together like husband and wife', 'Living together like husband and wife/partners', 'Married', 'Never married', 'Single and have never been married/never lived together as husband/wife before', 'Single, but have lived together with someone as husband/wife before', 'Widow/Widower', 'Widowed']
Race = Literal['African/Black', 'Coloured', 'Indian/Asian', 'White']
Geotype = Literal['Farms', 'Traditional', 'Urban']
ActorArchetype = Literal['affluent_agricultural_household', 'affluent_urban_household', 'civic_moderate', 'comfortable_household', 'communal_farmer', 'community_leader', 'disillusioned_dropout', 'educator', 'gogo_guardian', 'grant_dependent_survivor', 'guardian_parent', 'informal_trader', 'institutional_loyalist', 'learner', 'rural_landholding_household', 'small_business_owner', 'smallholder_emerging_farmer', 'unemployed_youth', 'urban_professional']
AttitudeMatchQuality = Literal['age_backoff', 'education_backoff', 'exact', 'province_backoff', 'status_race', 'race_only', 'population']
SourceSurvey = Literal['ghs_2025', 'qlfs_2026_q1']
OccupationProvenance = Literal['role_assigned']
EmploymentStatusProvenance = Literal['ghs_2025:employ_Status2']
HomeLanguage = Literal['Afrikaans', 'English', 'IsiNdebele', 'IsiXhosa', 'IsiZulu', 'Other language not specified', 'Sepedi', 'Sesotho', 'Setswana', 'SiSwati', 'Tshivenda', 'Xitsonga']
IncomeProvenance = Literal['ghs_2025_reported']
SelfRatedHealth = Literal['Excellent', 'Fair', 'Good', 'Poor', 'Very good']
UsualHealthFacility = Literal['Private sector: Clinic', 'Private sector: Hospital', 'Private sector: Pharmacy/chemist', 'Private sector: Private doctor/specialist', 'Private sector: Traditional healer', 'Public sector: Clinic', 'Public sector: Hospital']
HealthFacilitySector = Literal['private', 'public']
TransportToHealthFacility = Literal['Bus', 'Minibus taxi/sedan taxi/bakkie taxi', 'Other means of transport to nearest facility', 'Own transport', 'Walking']
TimeToHealthFacility = Literal['15–29 minutes', '30–89 minutes', '90 minutes and more', 'Less than 15 minutes']
HealthProvenance = Literal['ghs_2025_reported']
GhsRole = Literal['gogo_guardian', 'guardian_parent', 'learner']
EduInstitution = Literal['School', 'TVET college']
CurrentGrade = Literal['Grade 10', 'Grade 11', 'Grade 12/Matric', 'Grade 7', 'Grade 8', 'Grade 9', 'Not applicable']
FeesBand = Literal['No fees', 'R1 001–R2 000 per year', 'R12 001–R16 000 per year', 'R16 001–R20 000 per year', 'R2 001–R3 000 per year', 'R201–R300 per year', 'R301–R500 per year', 'R4 001–R8 000 per year']
TimeToSchool = Literal['15-30 minutes', '31-60 minutes', '61-90 minutes', 'under 15 minutes']
GuardianType = Literal['grandparent', 'other relative', 'parent']
LearnerFeeBands = Literal['No fees', 'R1 001–R2 000 per year', 'R101–R200 per year', 'R12 001–R16 000 per year', 'R1–R100 per year', 'R2 001–R3 000 per year', 'R20 001–R40 000 per year', 'R201–R300 per year', 'R3 001–R4 000 per year', 'R301–R500 per year', 'R40 001–R80 000 per year', 'R501–R1 000 per year', 'R8 001–R12 000 per year']
FarmMarketOrientation = Literal['market', 'subsistence']
FarmProducts = Literal['Farming of animals', 'Growing of crops', 'Growing of crops combined with farming of animals(mixed farming)']
AttitudeRowTopic = Literal['gov_trust', 'economic_optimism', 'service_satisfaction', 'crime_fear', 'education_satisfaction', 'health_service_satisfaction', 'health_authority_trust', 'councillor_responsiveness', 'official_responsiveness', 'crime_handling', 'immigration_priority', 'pays_for_quality', 'business_trust', 'social_trust', 'environment_priority', 'social_voice', 'neighbour_trust']
CircumstanceRowField = Literal['lived_poverty', 'went_without_care', 'owns_vehicle', 'owns_computer', 'owns_bank_account', 'owns_television', 'internet_use', 'owns_phone', 'phone_internet', 'phone_use', 'electricity_reliability', 'money_decision', 'news_radio', 'news_tv', 'news_internet', 'news_social', 'metro', 'dwelling', 'rdp_housing', 'learners_in_household', 'ghs_role', 'learner_fee_bands', 'medical_aid']
AttitudeRowSources = Literal['afrobarometer_r9_sa', 'afrobarometer_r9_sa:students', 'afrobarometer_r9_sa:teacher_class_professionals']
AttitudeRowMatchQuality = Literal['age_backoff', 'education_backoff', 'exact', 'population_draw', 'province_backoff', 'race_only', 'status_race', 'population']
CircumstanceRowSources = Literal['afrobarometer_r9_sa', 'afrobarometer_r9_sa:students', 'afrobarometer_r9_sa:teacher_class_professionals', 'ghs_2025', 'qlfs_2026_q1', 'ghs_2025:household']
CircumstanceRowMatchQuality = Literal['age_backoff', 'education_backoff', 'exact', 'population_draw', 'province_backoff', 'race_only', 'status_race', 'population', 'prov_geo_race_sex_age', 'prov_geo_race_sex', 'prov_geo_race', 'prov_geo', 'prov', 'geo_race_sex_age', 'geo_sex_age', 'sex_age', 'age', 'prov_geo_race_sex_age_hard_emp', 'geo_race_sex_age_hard_emp', 'sex_age_hard_emp', 'sex_age_hard']
TOPICS = {'gov_trust': {'stances': ['low', 'mid', 'high'],
               'source': {'survey': 'afrobarometer_r9_sa',
                          'items': ['Q37A', 'Q37D'],
                          'primary_item': 'Q37A',
                          'asked': 'how much you trust the President'},
               'answers': ['A lot', 'Just a little', 'Not at all', 'Somewhat']},
 'economic_optimism': {'stances': ['pessimistic', 'neutral', 'optimistic'],
                       'source': {'survey': 'afrobarometer_r9_sa',
                                  'items': ['Q4A', 'Q4B'],
                                  'primary_item': 'Q4A',
                                  'asked': 'the present economic condition of the country'},
                       'answers': ['Fairly bad',
                                   'Fairly good',
                                   'Neither good nor bad',
                                   'Very bad',
                                   'Very good']},
 'service_satisfaction': {'stances': ['dissatisfied', 'mixed', 'satisfied'],
                          'source': {'survey': 'afrobarometer_r9_sa',
                                     'items': ['Q46I', 'Q46L'],
                                     'primary_item': 'Q46I',
                                     'asked': 'how government is handling water and '
                                              'sanitation'},
                          'answers': ['Fairly badly',
                                      'Fairly well',
                                      'Very badly',
                                      'Very well']},
 'crime_fear': {'stances': ['low', 'mid', 'high'],
                'source': {'survey': 'afrobarometer_r9_sa',
                           'items': ['Q7A', 'Q7B'],
                           'primary_item': 'Q7A',
                           'asked': 'how often you felt unsafe walking in your neighbourhood'},
                'answers': ['Always',
                            'Just once or twice',
                            'Many times',
                            'Never',
                            'Several times']},
 'education_satisfaction': {'stances': ['dissatisfied', 'mixed', 'satisfied'],
                            'source': {'survey': 'afrobarometer_r9_sa',
                                       'items': ['Q46H'],
                                       'primary_item': 'Q46H',
                                       'asked': 'how government is handling educational needs'},
                            'answers': ['Fairly badly',
                                        'Fairly well',
                                        'Very badly',
                                        'Very well']},
 'health_service_satisfaction': {'stances': ['dissatisfied', 'mixed', 'satisfied'],
                                 'source': {'survey': 'afrobarometer_r9_sa',
                                            'items': ['Q46G'],
                                            'primary_item': 'Q46G',
                                            'asked': 'how government is handling basic health '
                                                     'services'},
                                 'answers': ['Fairly badly',
                                             'Fairly well',
                                             'Very badly',
                                             'Very well']},
 'health_authority_trust': {'stances': ['low', 'mid', 'high'],
                            'source': {'survey': 'afrobarometer_r9_sa',
                                       'items': ['Q37O_SAF'],
                                       'primary_item': 'Q37O_SAF',
                                       'asked': 'how much you trust the Department of Health'},
                            'answers': ['A lot', 'Just a little', 'Not at all', 'Somewhat']},
 'councillor_responsiveness': {'stances': ['low', 'mid', 'high'],
                               'source': {'survey': 'afrobarometer_r9_sa',
                                          'items': ['Q34B'],
                                          'primary_item': 'Q34B',
                                          'asked': 'how much your local councillor listens'},
                               'answers': ['Always', 'Never', 'Often', 'Only sometimes']},
 'official_responsiveness': {'stances': ['low', 'mid', 'high'],
                             'source': {'survey': 'afrobarometer_r9_sa',
                                        'items': ['Q36A'],
                                        'primary_item': 'Q36A',
                                        'asked': 'how much government officials listen'},
                             'answers': ['Not at all likely',
                                         'Not very likely',
                                         'Somewhat likely',
                                         'Very likely']},
 'crime_handling': {'stances': ['dissatisfied', 'mixed', 'satisfied'],
                    'source': {'survey': 'afrobarometer_r9_sa',
                               'items': ['Q46F'],
                               'primary_item': 'Q46F',
                               'asked': 'how government is handling crime'},
                    'answers': ['Fairly badly', 'Fairly well', 'Very badly', 'Very well']},
 'immigration_priority': {'stances': ['low', 'mid', 'high'],
                          'source': {'survey': 'afrobarometer_r9_sa',
                                     'items': ['Q82C_SAF'],
                                     'primary_item': 'Q82C_SAF',
                                     'asked': 'whether foreign nationals take jobs from '
                                              'locals'},
                          'answers': ['Agree',
                                      'Disagree',
                                      'Neither agree nor disagree',
                                      'Strongly agree',
                                      'Strongly disagree']},
 'pays_for_quality': {'stances': ['no', 'mixed', 'yes'],
                      'source': {'survey': 'afrobarometer_r9_sa',
                                 'items': ['Q80C_SAF'],
                                 'primary_item': 'Q80C_SAF',
                                 'asked': 'paying more for a better service'},
                      'answers': ['Agree',
                                  'Disagree',
                                  'Neither agree nor disagree',
                                  'Strongly agree',
                                  'Strongly disagree']},
 'business_trust': {'stances': ['low', 'mid', 'high'],
                    'source': {'survey': 'afrobarometer_r9_sa',
                               'items': ['Q38J'],
                               'primary_item': 'Q38J',
                               'asked': 'how much you trust private businesses'},
                    'answers': ['All of them', 'Most of them', 'None', 'Some of them']},
 'social_trust': {'stances': ['low', 'mid', 'high'],
                  'source': {'survey': 'afrobarometer_r9_sa',
                             'items': ['Q86A'],
                             'primary_item': 'Q86A',
                             'asked': 'whether most people can be trusted'},
                  'answers': ['A lot', 'Just a little', 'Not at all', 'Somewhat']},
 'environment_priority': {'stances': ['low', 'mid', 'high'],
                          'source': {'survey': 'afrobarometer_r9_sa',
                                     'items': ['Q67A', 'Q72A', 'Q72D']}},
 'social_voice': {'stances': ['low', 'mid', 'high'],
                  'source': {'survey': 'afrobarometer_r9_sa',
                             'items': ['Q8', 'Q10B'],
                             'primary_item': 'Q10B',
                             'asked': 'whether you have joined others to raise an issue'},
                  'answers': ['No, would do it if I had the chance',
                              'No, would never do this',
                              'Yes, often',
                              'Yes, once or twice',
                              'Yes, several times']},
 'neighbour_trust': {'stances': ['low', 'mid', 'high'],
                     'source': {'survey': 'afrobarometer_r9_sa',
                                'items': ['Q86C'],
                                'primary_item': 'Q86C',
                                'asked': 'how much you trust your neighbours'},
                     'answers': ['A lot', 'Just a little', 'Not at all', 'Somewhat']}}
CIRCUMSTANCES = {'lived_poverty': {'values': ['none', 'low', 'moderate', 'high'],
                   'source': {'survey': 'afrobarometer_r9_sa',
                              'items': ['Q6A', 'Q6B', 'Q6C', 'Q6D', 'Q6E']},
                   'prompt': {'core': True,
                              'say': {'none': 'This year you have had enough food, water and '
                                              'cash.',
                                      'low': 'Once or twice this year you were short of '
                                             'something basic.',
                                      'moderate': 'Several times this year you were short of '
                                                  'food, water or cash.',
                                      'high': 'You are often short of food, water or cash.'}}},
 'went_without_care': {'values': ['never', 'rarely', 'sometimes', 'often'],
                       'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q6C']},
                       'prompt': {'about': ['health'],
                                  'say': {'never': 'You have been able to get medical care '
                                                   'when you needed it.',
                                          'rarely': 'Once or twice this year you could not get '
                                                    'medical care you needed.',
                                          'sometimes': 'Several times this year you could not '
                                                       'get medical care you needed.',
                                          'often': 'You often cannot get the medical care you '
                                                   'need.'}}},
 'owns_vehicle': {'values': ['none', 'household', 'own'],
                  'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90C']},
                  'prompt': {'about': ['getting_there'],
                             'say': {'none': 'There is no car in your household.',
                                     'household': 'There is a car in your household you can '
                                                  'use.',
                                     'own': 'You have your own car.'}}},
 'owns_computer': {'values': ['none', 'household', 'own'],
                   'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90D']},
                   'prompt': {'about': ['online'],
                              'say': {'none': 'There is no computer in your household.',
                                      'household': 'There is a computer in your household that '
                                                   'you share.',
                                      'own': 'You have your own computer.'},
                              'replaced_by': 'computer_in_home'}},
 'owns_bank_account': {'values': ['none', 'household', 'own'],
                       'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90E']},
                       'prompt': {'about': ['money'],
                                  'say': {'none': 'You do not have a bank account.',
                                          'household': "You use someone else's bank account in "
                                                       'your household.',
                                          'own': 'You have your own bank account.'}}},
 'owns_television': {'values': ['none', 'household', 'own'],
                     'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90B']},
                     'prompt': {'about': ['media'],
                                'say': {'none': 'There is no TV in your household.',
                                        'household': 'There is a TV in your household.',
                                        'own': 'You have your own TV.'}}},
 'internet_use': {'values': ['never', 'rarely', 'monthly', 'weekly', 'daily'],
                  'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90I']},
                  'note': 'What the person calls "the internet". In R9 SA, 240 of the 360 who '
                          'said never own a mobile phone and 206 use one every day, so never '
                          'here is not "no WhatsApp". The phone facts carry that.',
                  'prompt': {'about': ['online', 'media'],
                             'say': {'never': 'You say you never use the internet.',
                                     'rarely': 'You go online less than once a month.',
                                     'monthly': 'You go online a few times a month.',
                                     'weekly': 'You go online a few times a week.',
                                     'daily': 'You go online every day.'}}},
 'owns_phone': {'values': ['none', 'household', 'own'],
                'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90F']},
                'optional': True,
                'note': 'Added after the library was built. Only a persona whose survey '
                        'respondent still gives every other circumstance it carries has it '
                        '(scripts/attach_phone_facts.py).',
                'prompt': {'about': ['online'],
                           'say': {'none': 'No one in your household has a mobile phone.',
                                   'household': 'You have no mobile phone of your own; someone '
                                                'else in your household has one.',
                                   'own': 'You have your own mobile phone.'}}},
 'phone_internet': {'values': ['no', 'yes'],
                    'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90G']},
                    'optional': True,
                    'note': 'Only asked of people who own a phone themselves.',
                    'prompt': {'about': ['online'],
                               'say': {'no': 'Your phone cannot get on the internet.',
                                       'yes': 'Your phone can get on the internet.'}}},
 'phone_use': {'values': ['never', 'rarely', 'monthly', 'weekly', 'daily'],
               'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q90H']},
               'optional': True,
               'prompt': {'about': ['online'],
                          'say': {'never': 'You never use a mobile phone.',
                                  'rarely': 'You use a mobile phone less than once a month.',
                                  'monthly': 'You use a mobile phone a few times a month.',
                                  'weekly': 'You use a mobile phone a few times a week.',
                                  'daily': 'You use a mobile phone every day.'}}},
 'electricity_reliability': {'values': ['never', 'occasional', 'half', 'most', 'always'],
                             'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q92B']},
                             'prompt': {'about': ['services'],
                                        'say': {'never': 'There is no reliable mains power '
                                                         'where you live.',
                                                'occasional': 'The power is on only now and '
                                                              'then.',
                                                'half': 'The power is on about half the time.',
                                                'most': 'The power is on most of the time, '
                                                        'with interruptions.',
                                                'always': 'The power stays on where you '
                                                          'live.'}}},
 'money_decision': {'values': ['self', 'joint', 'other', 'none'],
                    'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q93C']},
                    'prompt': {'about': ['money'],
                               'say': {'self': 'You decide how the money in your household is '
                                               'spent.',
                                       'joint': 'You and others in your household decide '
                                                'together how money is spent.',
                                       'other': 'Someone else in your household decides how '
                                                'money is spent.',
                                       'none': 'You have no say in how money is spent.'}}},
 'news_radio': {'values': ['never', 'rarely', 'monthly', 'weekly', 'daily'],
                'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q74A']},
                'prompt': {'about': ['media'],
                           'say': {'never': 'You never hear news on the radio.',
                                   'rarely': 'You hear news on the radio less than once a '
                                             'month.',
                                   'monthly': 'You hear news on the radio a few times a month.',
                                   'weekly': 'You hear news on the radio a few times a week.',
                                   'daily': 'You hear news on the radio every day.'}}},
 'news_tv': {'values': ['never', 'rarely', 'monthly', 'weekly', 'daily'],
             'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q74B']},
             'prompt': {'about': ['media'],
                        'say': {'never': 'You never watch news on TV.',
                                'rarely': 'You watch news on TV less than once a month.',
                                'monthly': 'You watch news on TV a few times a month.',
                                'weekly': 'You watch news on TV a few times a week.',
                                'daily': 'You watch news on TV every day.'}}},
 'news_internet': {'values': ['never', 'rarely', 'monthly', 'weekly', 'daily'],
                   'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q74D']},
                   'prompt': {'about': ['media', 'online'],
                              'say': {'never': 'You never read news on the internet.',
                                      'rarely': 'You read news on the internet less than once '
                                                'a month.',
                                      'monthly': 'You read news on the internet a few times a '
                                                 'month.',
                                      'weekly': 'You read news on the internet a few times a '
                                                'week.',
                                      'daily': 'You read news on the internet every day.'}}},
 'news_social': {'values': ['never', 'rarely', 'monthly', 'weekly', 'daily'],
                 'source': {'survey': 'afrobarometer_r9_sa', 'items': ['Q74E']},
                 'prompt': {'about': ['media', 'online'],
                            'say': {'never': 'You never get news from social media.',
                                    'rarely': 'You get news from social media less than once a '
                                              'month.',
                                    'monthly': 'You get news from social media a few times a '
                                               'month.',
                                    'weekly': 'You get news from social media a few times a '
                                              'week.',
                                    'daily': 'You get news from social media every day.'}}},
 'metro': {'values': ['WC - Non-metro',
                      'WC - City of Cape Town',
                      'EC - Non-metro',
                      'EC - Buffalo City',
                      'EC - Nelson Mandela Bay',
                      'NC - Non-metro',
                      'FS - Non-metro',
                      'FS - Mangaung',
                      'KZN - Non-metro',
                      'KZN - eThekwini',
                      'NW - Non-metro',
                      'GP - Non-metro',
                      'GP - Ekurhuleni',
                      'GP - City of Johannesburg',
                      'GP - City of Tshwane',
                      'MP - Non-metro',
                      'LP - Non-metro'],
           'source': {'survey': 'qlfs_2026_q1', 'items': ['Metro_code']},
           'note': 'Where the persona lives, at the finest level the surveys measure. A '
                   "persona sampled from QLFS carries its own survey row's metro (real, "
                   "match_quality 'exact'); the library's original 375 predate that and carry "
                   'one drawn from the GHS spread for people like them '
                   '(scripts/add_ghs_geography.py), with `share` saying how sure that '
                   'placement is. No prompt block on purpose -- a persona must not claim to be '
                   'from a place the survey never put them in.'},
 'dwelling': {'values': ['house_own_stand',
                         'traditional_dwelling',
                         'flat',
                         'complex_house',
                         'backyard_room',
                         'backyard_shack',
                         'informal_settlement',
                         'room_on_property',
                         'other_dwelling'],
              'source': {'survey': 'ghs_2025', 'items': ['hsg_maind']},
              'note': "The kind of home, collapsed from GHS's 12 dwelling types. Backyard and "
                      "informal dwellings are what 'township' means here -- GHS has no "
                      'township flag, so this is the measured proxy. Imputed the same way as '
                      'metro.'},
 'rdp_housing': {'values': ['yes', 'no'],
                 'source': {'survey': 'ghs_2025', 'items': ['hsg_rdp']},
                 'note': 'Lives in an RDP or state-subsidised house. Imputed the same way as '
                         'metro.'},
 'learners_in_household': {'values': ['0', '1', '2', '3', '4'],
                           'source': {'survey': 'ghs_2025',
                                      'items': ['edu_attend', 'edu_edui', 'age']},
                           'optional': True,
                           'note': 'School-system learners aged 6-18 in the household; 4 means '
                                   'four or more. Imputed from a matched real GHS adult '
                                   '(scripts/add_ghs_household.py), never measured on this '
                                   'persona: the row carries pool, share and grade. A value on '
                                   "the persona's own survey row wins."},
 'ghs_role': {'values': ['learner', 'guardian_parent', 'gogo_guardian'],
              'source': {'survey': 'ghs_2025', 'items': ['hhc_relationship']},
              'optional': True,
              'note': "Only written when it applies. guardian_parent covers the head's own "
                      "adult child whose learner is the head's grandchild, always graded weak. "
                      'Imputed from a matched real GHS adult (scripts/add_ghs_household.py), '
                      'never measured on this persona: the row carries pool, share and grade. '
                      "A value on the persona's own survey row wins."},
 'learner_fee_bands': {'values': ['No fees',
                                  'R1–R100 per year',
                                  'R101–R200 per year',
                                  'R201–R300 per year',
                                  'R301–R500 per year',
                                  'R501–R1 000 per year',
                                  'R1 001–R2 000 per year',
                                  'R2 001–R3 000 per year',
                                  'R3 001–R4 000 per year',
                                  'R4 001–R8 000 per year',
                                  'R8 001–R12 000 per year',
                                  'R12 001–R16 000 per year',
                                  'R16 001–R20 000 per year',
                                  'R20 001–R40 000 per year',
                                  'R40 001–R80 000 per year',
                                  'More than R80 000 per year'],
                       'source': {'survey': 'ghs_2025', 'items': ['edu_totfees']},
                       'optional': True,
                       'note': 'The dearest annual fee band a learner in the household pays. '
                               'Imputed from a matched real GHS adult '
                               '(scripts/add_ghs_household.py), never measured on this '
                               'persona: the row carries pool, share and grade. A value on the '
                               "persona's own survey row wins."},
 'medical_aid': {'values': ['True', 'False'],
                 'source': {'survey': 'ghs_2025', 'items': ['hlt_medi']},
                 'optional': True,
                 'note': 'Covered by a medical aid scheme. Imputed from a matched real GHS '
                         'adult (scripts/add_ghs_household.py), never measured on this '
                         'persona: the row carries pool, share and grade. A value on the '
                         "persona's own survey row wins."}}
DERIVED_FACTS = {'age_band': {'values': ['15-24', '25-34', '35-59', '60+'],
              'from': 'age',
              'note': 'Made at match time by mechanism_card_service._age_band. Not stored.'},
 'youth_age_band': {'values': ['under-16', '16-17', '18-24', '25+'],
                    'from': 'age',
                    'note': 'Made at match time by mechanism_card_service._youth_age_band. Not '
                            'stored. Finer than age_band for research on young people: studies '
                            'recruit from 16 or 18.'}}
GROUPS = {'everyone': {'when': {}, 'about': 'Every library persona.'},
 'ghs_household': {'when': {'source_survey': ['ghs_2025']},
                   'about': 'Built from the GHS 2025 household files.'},
 'ghs_household_build': {'when': {'source_survey': ['ghs_2025'], 'ghs_role': [None]},
                         'about': 'GHS households sampled by money and land (affluent, '
                                  'comfortable, landholding).'},
 'ghs_role_build': {'when': {'source_survey': ['ghs_2025'],
                             'ghs_role': ['learner', 'guardian_parent', 'gogo_guardian']},
                    'about': 'GHS learners and the adults who look after them.'},
 'learner': {'when': {'ghs_role': ['learner']}, 'about': 'School and college learners.'},
 'guardian': {'when': {'ghs_role': ['guardian_parent', 'gogo_guardian']},
              'about': 'Parents and grandparents with learners at home.'},
 'farmer': {'when': {'actor_archetype': ['communal_farmer', 'smallholder_emerging_farmer']},
            'about': 'QLFS farm-module samples.'}}
