# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── grant_schedule ──────────────────────────────────────────────────────────
GrantScheduleCurrency = Literal['ZAR']

# ── world_facts ─────────────────────────────────────────────────────────────
WorldFactsCurrency = Literal['ZAR']
