# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── ipc_command ─────────────────────────────────────────────────────────────
IpcCommandCommandType = Literal['interview', 'batch_interview', 'close_env', 'pause', 'resume', 'apply_intervention', 'broadcast_intervention']

# ── ipc_response ────────────────────────────────────────────────────────────
IpcResponseStatus = Literal['pending', 'processing', 'completed', 'failed']

# ── sim_action ──────────────────────────────────────────────────────────────
SimActionPlatform = Literal['opinion_space']
SimActionActionType = Literal['EXPRESS_OPINION', 'RESPOND_TO_OPINION', 'SEARCH_TOPIC', 'OBSERVE', 'DO_NOTHING', 'NON_PARTICIPATION', 'SYSTEM_EVENT']

# ── sim_document_context ────────────────────────────────────────────────────
SimDocumentContextMode = Literal['policy', 'product']
SimDocumentContextSecondaryLens = Literal['policy', 'product']

# ── sim_log_marker ──────────────────────────────────────────────────────────
SimLogMarkerEventType = Literal['round_end', 'simulation_end']

# ── sim_report ──────────────────────────────────────────────────────────────
SimReportStatus = Literal['pending', 'planning', 'generating', 'completed', 'failed']

# ── sim_report_progress ─────────────────────────────────────────────────────
SimReportProgressStatus = Literal['pending', 'planning', 'generating', 'completed', 'failed']

# ── sim_run_state ───────────────────────────────────────────────────────────
SimRunStateRunnerStatus = Literal['idle', 'starting', 'running', 'paused', 'stopping', 'stopped', 'completed', 'failed']

# ── sim_state ───────────────────────────────────────────────────────────────
SimStateStatus = Literal['created', 'preparing', 'ready', 'running', 'paused', 'stopped', 'completed', 'failed']
