# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── custom_agent ────────────────────────────────────────────────────────────
CustomAgentStance = Literal['support', 'neutral', 'concerned', 'oppose', 'resist']
CustomAgentSourceEntityType = Literal['custom', 'custom_manual']

# ── hypothesis_report ───────────────────────────────────────────────────────
HypothesisReportMode = Literal['panel', 'product', 'policy']

# ── mechanism_card ──────────────────────────────────────────────────────────
MechanismCardClaimType = Literal['qualitative', 'mixed_methods']

# ── panel_context ───────────────────────────────────────────────────────────
PanelContextMode = Literal['panel', 'product', 'policy']
PanelContextPanelSession = Literal[True]

# ── panel_session ───────────────────────────────────────────────────────────
PanelSessionMode = Literal['panel', 'product', 'policy']

# ── poster ──────────────────────────────────────────────────────────────────
PosterMimeType = Literal['image/png', 'image/jpeg', 'image/jpg', 'image/webp']

# ── project ─────────────────────────────────────────────────────────────────
ProjectStatus = Literal['created', 'ontology_generated', 'graph_building', 'graph_completed', 'failed']
