# Generated by scripts/generate_model_types.py from the catalogues in
# app/data/model/catalogue/. Do not edit by hand.


from typing import Literal


# ── custom_agent ────────────────────────────────────────────────────────────
CustomAgentStance = Literal['support', 'neutral', 'concerned', 'oppose', 'resist']
CustomAgentSourceEntityType = Literal['custom', 'custom_manual']

# ── hypothesis_report ───────────────────────────────────────────────────────
HypothesisReportMode = Literal['panel', 'product', 'policy']
HypothesisReportMovementPeopleItemDirection = Literal['warmer', 'cooler', 'sideways']

# ── local_papers ────────────────────────────────────────────────────────────
LocalPapersPapersItemSource = Literal['arxiv', 'openalex', 'crossref', 'local']

# ── mechanism_card ──────────────────────────────────────────────────────────
MechanismCardClaimType = Literal['qualitative', 'mixed_methods']
MechanismCardEconomicTags = Literal['tight', 'moderate', 'loose']
MechanismCardCombGaps = Literal['capability', 'opportunity', 'motivation']

# ── panel_context ───────────────────────────────────────────────────────────
PanelContextMode = Literal['panel', 'product', 'policy']
PanelContextPanelSession = Literal[True]

# ── panel_session ───────────────────────────────────────────────────────────
PanelSessionMode = Literal['panel', 'product', 'policy']
PanelSessionBudgetTierFilter = Literal['tight', 'moderate', 'loose']
PanelSessionAffordabilityFromPriceTiers = Literal['tight', 'moderate', 'loose']
PanelSessionSlotsProbesItemConfidence = Literal['strong-data', 'thin-data']
PanelSessionPlaceLevel = Literal['metro', 'province']

# ── poster ──────────────────────────────────────────────────────────────────
PosterMimeType = Literal['image/png', 'image/jpeg', 'image/jpg', 'image/webp']

# ── project ─────────────────────────────────────────────────────────────────
ProjectStatus = Literal['created', 'ontology_generated', 'graph_building', 'graph_completed', 'failed']
