"""Write app/models/_<module>_types.py from the authored catalogues.

A stored thing is described in two halves:

    app/data/model/catalogue/<name>.json   the data — allowed survey answers, the
                                           tables a persona is checked against, and
                                           the notes saying where each field came from
    app/models/<module>.py                 the class — field names, Python types, methods

Python needs the answer lists as types at import time, so they are generated into
app/models/_<module>_types.py and the class imports them. That file is never
hand-edited, and the class holds no data of its own.

    python backend/scripts/generate_model_types.py          # rewrite the files
    python backend/scripts/generate_model_types.py --check  # exit 1 if any is stale

tests/test_model_catalogue.py fails when a generated file drifts from its catalogue.
"""

from __future__ import annotations

import argparse
import json
import os
import pprint
import sys

BACKEND = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MODEL_DIR = os.path.join(BACKEND, "app", "data", "model")
MODELS_DIR = os.path.join(BACKEND, "app", "models")

BANNER = ("# Generated by scripts/generate_model_types.py from the catalogues in\n"
          "# app/data/model/catalogue/. Do not edit by hand.\n")

#: Generated constant -> where its table sits in the exported file. A section path means
#: the table hangs off a row section: CIRCUMSTANCES is circumstance_row["fields"], which
#: is why a plain key lookup would have generated an incomplete file.
TABLES = {
    "TOPICS": ("attitude_row", "topics"),
    "CIRCUMSTANCES": ("circumstance_row", "fields"),
    "DERIVED_FACTS": ("derived_facts",),
    "GROUPS": ("groups",),
}


def alias(*parts: str) -> str:
    """province -> Province; attitude_row + topic -> AttitudeRowTopic.

    A part that is already CamelCase (an inner class name like
    `EventRulesRulesItemTrigger`) is kept as it is: capitalize() would lowercase the
    rest of the word and give `Eventrulesrulesitemtrigger`, which still imports fine
    and so would never have failed loudly.
    """
    out = []
    for part in parts:
        if "_" not in part and part[:1].isupper():
            out.append(part)
        else:
            out += [p.capitalize() for p in part.split("_")]
    return "".join(out)


def _literal(values) -> str:
    return "Literal[" + ", ".join(repr(v) for v in values) + "]"


def _model_names(module: str) -> list:
    """The models a module owns, in the order their files appear."""
    sys.path.insert(0, BACKEND)
    os.environ.setdefault("AGENTSOCIETY_LLM_API_KEY", "generate-placeholder")
    from app.models import REGISTRY
    return sorted(name for name, cls in REGISTRY.items()
                  if cls.__module__.rsplit(".", 1)[-1] == module)


def _exported(name: str) -> dict:
    with open(os.path.join(MODEL_DIR, f"{name}.json"), encoding="utf-8") as fh:
        return json.load(fh)


def _class_name(name: str) -> str:
    """The Python class a model name belongs to (persona -> LibraryPersona)."""
    sys.path.insert(0, BACKEND)
    os.environ.setdefault("AGENTSOCIETY_LLM_API_KEY", "generate-placeholder")
    from app.models import REGISTRY
    return REGISTRY[name].__name__


def _nested(spec: dict, holder: str) -> list:
    """(inner class name, field, allowed) for every field in a nested field table.

    The inner classes are named after the path that reaches them, so the path predicts
    the name: `values` contributes "Value", a list's `items` contributes "Item".
    """
    out = []
    table = spec.get("fields")
    if not isinstance(table, dict):
        return out
    for field, sub in table.items():
        if not isinstance(sub, dict):
            continue
        if isinstance(sub.get("fields"), dict):
            inner = holder + alias(field)
            for f, s in sub["fields"].items():
                if isinstance(s, dict) and s.get("allowed"):
                    out.append((inner, f, s["allowed"]))
            out += _nested(sub, inner)
        for key, suffix in (("items", "Item"), ("values", "Value")):
            held = sub.get(key)
            if isinstance(held, dict) and isinstance(held.get("fields"), dict):
                inner = holder + alias(field) + suffix
                for f, s in held["fields"].items():
                    if isinstance(s, dict) and s.get("allowed"):
                        out.append((inner, f, s["allowed"]))
                out += _nested(held, inner)
    return out


def rendered(module: str) -> str:
    """The generated types module for one app/models file.

    A module owning several models prefixes each alias with its model name, because the
    same field name carries different answers in different models (`status` means three
    things in both accounts and simulation). A module owning one model needs no prefix,
    so the class reads `province: Province`.
    """
    names = _model_names(module)
    prefixed = len(names) > 1
    lines = [BANNER, "", "from typing import Literal", ""]
    for name in names:
        doc = _exported(name)
        chunk = []
        for field, spec in (doc.get("fields") or {}).items():
            if isinstance(spec, dict) and spec.get("allowed"):
                alias_name = alias(name, field) if prefixed else alias(field)
                chunk.append(f"{alias_name} = {_literal(spec['allowed'])}")
        # Nested field tables: an object field's `fields`, a list's `items.fields`, a
        # free-key map's `values.fields`. Each is held by its own inner class, whose name
        # the path predicts (EventRules + rules + items + trigger ->
        # EventRulesRulesItemTrigger). Checked against every inner class: 10/10.
        for inner_cls, inner_field, allowed in _nested(doc, _class_name(name)):
            chunk.append(f"{alias(inner_cls, inner_field)} = {_literal(allowed)}")
        for section in ("attitude_row", "circumstance_row"):
            row = doc.get(section)
            if not isinstance(row, dict):
                continue
            for key in ("sources", "match_quality"):
                if row.get(key):
                    chunk.append(f"{alias(section, key)} = {_literal(row[key])}")
        for const, path in TABLES.items():
            table = doc
            for step in path:
                table = table.get(step) if isinstance(table, dict) else None
            if isinstance(table, dict):
                chunk.append(f"{const} = " + pprint.pformat(table, width=96, sort_dicts=False))
        if chunk:
            lines.append("")
            lines.append(f"# ── {name} ".ljust(78, "─"))
            lines += chunk
    return "\n".join(lines).rstrip("\n") + "\n"


def target(module: str) -> str:
    return os.path.join(MODELS_DIR, f"_{module}_types.py")


def has_content(text: str) -> bool:
    """True when a rendered module actually defines something (not just the banner)."""
    return any(line and not line.startswith(("#", "from ", "import "))
               for line in text.splitlines())


def modules() -> list:
    """Model modules that own at least one field with allowed answers, or a table."""
    out = []
    for fname in sorted(os.listdir(MODELS_DIR)):
        if not fname.endswith(".py") or fname.startswith("_") or fname == "base.py":
            continue
        module = fname[:-3]
        if has_content(rendered(module)):
            out.append(module)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report staleness instead of writing")
    ap.add_argument("--module", help="only this module")
    args = ap.parse_args()

    names = [args.module] if args.module else modules()
    stale, wrote = [], 0
    for module in names:
        want = rendered(module)
        path = target(module)
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if args.check:
            if want != have:
                stale.append(module)
            continue
        if want != have:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(want)
            wrote += 1
    if args.check:
        for module in stale:
            print(f"stale: app/models/_{module}_types.py "
                  f"(run scripts/generate_model_types.py)")
        return 1 if stale else 0
    print(f"checked {len(names)} module(s); wrote {wrote}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
