"""
Simulation-related API routes
Step2: Entity reading and filtering, OASIS simulation preparation and execution (fully automated)
"""

import os
import json
import traceback
import asyncio
from typing import Optional
from flask import request, jsonify, current_app

from . import simulation_bp
from ..auth import current_user_id
from ..controllers import gates
from ..services import billing_service
from ..config import Config
from ..services.entity_reader import EntityReader
from ..services.simulation_manager import SimulationManager, SimulationStatus
from ..services.simulation_runner import SimulationRunner, RunnerStatus
from ..services.interview_service import InterviewService
from ..services.custom_agent_parser import CustomAgentParser
from ..services.agent_enricher import AgentContextEnricher
from ..services import mode_detector
from ..repositories import operator_context_repository as oc_service
from ..services.sim_presets import SIM_PRESETS, apply_preset
from ..utils.logger import get_logger
from ..repositories import project_repository

logger = get_logger('fub.api.simulation')


# ============== Custom Agent Parsing ==============

@simulation_bp.route('/custom-agents/parse', methods=['POST'])
def parse_custom_agent_document():
    """
    Parse a custom agent definition document.

    Supports JSON files (direct AgentProfile-compatible arrays)
    and unstructured text (PDF, MD, TXT) via LLM extraction.

    Request: multipart/form-data with 'file' field

    Returns:
        {
            "success": true,
            "data": [ {agent_profile}, ... ]
        }
    """
    try:
        from werkzeug.utils import secure_filename

        if 'file' not in request.files:
            return jsonify({"success": False, "error": "No file provided"}), 400

        file = request.files['file']
        if file.filename == '':
            return jsonify({"success": False, "error": "Empty filename"}), 400

        # Save uploaded file temporarily
        upload_dir = os.path.join(Config.UPLOAD_FOLDER, 'temp')
        os.makedirs(upload_dir, exist_ok=True)
        filename = secure_filename(file.filename)
        file_path = os.path.join(upload_dir, filename)
        file.save(file_path)

        # Get optional simulation context
        simulation_requirement = request.form.get('simulation_requirement', '')

        parser = CustomAgentParser()
        profiles = parser.parse_doc(file_path, simulation_requirement)

        # Clean up temp file
        try:
            os.remove(file_path)
        except Exception:
            pass

        # Serialize profiles for response
        data = [p.to_agentsociety_format() for p in profiles]

        return jsonify({
            "success": True,
            "data": data,
            "count": len(data)
        })

    except Exception as e:
        logger.error(f"Failed to parse custom agent document: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


# ============== Simulation management interface ==============

@simulation_bp.route('/create', methods=['POST'])
def create_simulation():
    """
    Create new simulation
    
    Note: parameters like max_rounds are intelligently generated by LLM, no manual setting needed
    
    Request (JSON):
        {
            "project_id": "proj_xxxx",  // Required
            "graph_id": "fub_xxxx"      // Optional, if not provided, get from project
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "project_id": "proj_xxxx",
                "graph_id": "fub_xxxx",
                "status": "created",
                "created_at": "2025-12-01T10:00:00"
            }
        }
    """
    # Simulations are paid, with a free trial (FREE_SIM_LIMIT) for closed-beta
    # testing while Paystack approval is pending. The quota is checked here so a
    # user is told up front they are out of runs; the credit itself is charged
    # only when the run actually starts (see /start), so a sim that is created
    # but never started costs nothing.
    gate = gates.sim_quota(current_user_id())
    if gate is not None:
        return gate
    try:
        data = request.get_json() or {}

        project_id = data.get('project_id')
        if not project_id:
            return jsonify({
                "success": False,
                "error": "Please provide project_id"
            }), 400
        
        project = project_repository.get(project_id)
        if not project:
            return jsonify({
                "success": False,
                "error": f"Project does not exist: {project_id}"
            }), 404
        
        graph_id = data.get('graph_id') or project.graph_id
        if not graph_id:
            return jsonify({
                "success": False,
                "error": "Project has not built knowledge graph yet, please call /api/graph/build first"
            }), 400
        
        manager = SimulationManager()
        state = manager.create_simulation(
            project_id=project_id,
            graph_id=graph_id,
            user_id=current_user_id(),
        )

        # No charge here — the sim credit is taken at /start, once the run
        # actually begins (see start_simulation).
        return jsonify({
            "success": True,
            "data": state.to_dict()
        })
        
    except Exception as e:
        logger.error(f"Failed to create simulation: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


def _check_simulation_prepared(simulation_id: str) -> tuple:
    """
    Check if simulation is ready
    
    Check conditions:
    1. state.json exists and status is "ready"
    2. Required files exist: reddit_profiles.json, twitter_profiles.csv, simulation_config.json
    
    Note: run scripts (run_*.py) remain in backend/scripts/ directory, no longer copied to simulation directory
    
    Args:
        simulation_id: Simulation ID
        
    Returns:
        (is_prepared: bool, info: dict)
    """
    import os
    from ..config import Config
    
    simulation_dir = os.path.join(Config.OASIS_SIMULATION_DATA_DIR, simulation_id)
    
    # Check if directory exists
    if not os.path.exists(simulation_dir):
        return False, {"reason": "Simulation directory does not exist"}
    
    required_files = [
        "state.json",
        "simulation_config.json",
        "agentsociety_profiles.json",
    ]
    
    # Check if files exist
    existing_files = []
    missing_files = []
    for f in required_files:
        file_path = os.path.join(simulation_dir, f)
        if os.path.exists(file_path):
            existing_files.append(f)
        else:
            missing_files.append(f)
    
    if missing_files:
        return False, {
            "reason": "Missing required files",
            "missing_files": missing_files,
            "existing_files": existing_files
        }
    
    # Check status in state.json
    state_file = os.path.join(simulation_dir, "state.json")
    try:
        with open(state_file, 'r', encoding='utf-8') as f:
            state_data = json.load(f)
        
        status = state_data.get("status", "")
        config_generated = state_data.get("config_generated", False)
        
        # Detailed logs
        logger.debug(f"Detect simulation preparation status: {simulation_id}, status={status}, config_generated={config_generated}")
        
        # If config_generated=True and files exist, consider preparation complete
        # The following statuses indicate preparation is complete：
        # - ready: Preparation complete, can run
        # - preparing: If config_generated=True, description shows completed
        # - running: Running, preparation already completed
        # - completed: Execution complete, preparation already completed
        # - stopped: Stopped, preparation already completed
        # - failed: Execution failed (but preparation is not completed)
        prepared_statuses = ["ready", "preparing", "running", "completed", "stopped", "failed", "paused"]
        if status in prepared_statuses and config_generated:
            # Get file statistics
            profiles_file = os.path.join(simulation_dir, "agentsociety_profiles.json")
            config_file = os.path.join(simulation_dir, "simulation_config.json")
            
            profiles_count = 0
            if os.path.exists(profiles_file):
                with open(profiles_file, 'r', encoding='utf-8') as f:
                    profiles_data = json.load(f)
                    profiles_count = len(profiles_data) if isinstance(profiles_data, list) else 0
            
            # If status is "preparing" but files are completed, update status to "ready"
            if status == "preparing":
                try:
                    state_data["status"] = "ready"
                    from datetime import datetime
                    state_data["updated_at"] = datetime.now().isoformat()
                    with open(state_file, 'w', encoding='utf-8') as f:
                        json.dump(state_data, f, ensure_ascii=False, indent=2)
                    logger.info(f"Auto update simulation status: {simulation_id} preparing -> ready")
                    status = "ready"
                except Exception as e:
                    logger.warning(f"Failed to auto update status: {e}")
            
            logger.info(f"Simulation {simulation_id} Detection result: HasPreparation complete (status={status}, config_generated={config_generated})")
            return True, {
                "status": status,
                "entities_count": state_data.get("entities_count", 0),
                "profiles_count": profiles_count,
                "entity_types": state_data.get("entity_types", []),
                "config_generated": config_generated,
                "created_at": state_data.get("created_at"),
                "updated_at": state_data.get("updated_at"),
                "existing_files": existing_files
            }
        else:
            logger.warning(f"Simulation {simulation_id} Detection result: Has notPreparation complete (status={status}, config_generated={config_generated})")
            return False, {
                "reason": f"Status not in prepared list or config_generated is false: status={status}, config_generated={config_generated}",
                "status": status,
                "config_generated": config_generated
            }
            
    except Exception as e:
        return False, {"reason": f"Failed to read state file: {str(e)}"}


@simulation_bp.route('/prepare', methods=['POST'])
def prepare_simulation():
    """
    Prepare simulation environment (async task with LLM intelligent configuration generation).

    This is a time-consuming operation. The interface returns immediately with a task_id.
    Use GET /api/simulation/prepare/status to query progress.

    Features:
    - Automatically detect completed preparations to avoid duplicate generation
    - If already prepared, return existing results directly
    - Support forced regeneration (force_regenerate=true)

    Steps:
    1. Check if preparation is already complete
    2. Read and filter entities from knowledge graph
    3. Generate OASIS Agent Profile for each entity (with retry mechanism)
    4. LLM intelligently generates simulation configuration (with retry mechanism)
    5. Save configuration files and preset scripts
    
    Request (JSON):
        {
            "simulation_id": "sim_xxxx",                   // Required，Simulation ID
            "entity_types": ["Student", "PublicFigure"],  // Optional，Specified entity type
            "parallel_profile_count": 5,                  // Optional, number of personas to generate in parallel, default 5
            "force_regenerate": false                     // Optional，ForceGenerate，Defaultfalse
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "task_id": "task_xxxx",           // Return for new tasks
                "status": "preparing|ready",
                "message": "Preparation task started|Preparation already completed",
                "already_prepared": true|false    // Is preparation complete
            }
        }
    """
    import threading
    import os
    from ..models.task import TaskManager, TaskStatus
    from ..config import Config

    # No paywall here: a sim is gated at create (check_sim_quota) and its
    # credit is charged at /start, so preparing an already-created sim must
    # always be allowed for its owner.

    try:
        data = request.get_json() or {}

        simulation_id = data.get('simulation_id')
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400
        
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)
        
        if not state:
            return jsonify({
                "success": False,
                "error": f"Simulation does not exist: {simulation_id}"
            }), 404
        
        # Check if forced regeneration
        force_regenerate = data.get('force_regenerate', False)
        logger.info(f"Start processing /prepare Request: simulation_id={simulation_id}, force_regenerate={force_regenerate}")
        
        # Check if already prepared（Avoid duplicatesGenerate）
        if not force_regenerate:
            logger.debug(f"Check simulation {simulation_id} Is preparation complete...")
            is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
            logger.debug(f"Check result: is_prepared={is_prepared}, prepare_info={prepare_info}")
            if is_prepared:
                logger.info(f"Simulation {simulation_id} has preparation complete, no need to regenerate")
                return jsonify({
                    "success": True,
                    "data": {
                        "simulation_id": simulation_id,
                        "status": "ready",
                        "message": "Preparation already completed，No need to repeatGenerate",
                        "already_prepared": True,
                        "prepare_info": prepare_info
                    }
                })
            else:
                logger.info(f"Simulation {simulation_id} has no preparation complete, preparing now")
        
        # Get necessary information from project
        project = project_repository.get(state.project_id)
        if not project:
            return jsonify({
                "success": False,
                "error": f"Project does not exist: {state.project_id}"
            }), 404
        
        # Get simulation requirements
        simulation_requirement = project.simulation_requirement or ""
        if not simulation_requirement:
            return jsonify({
                "success": False,
                "error": "Project missing simulation requirement description (simulation_requirement)"
            }), 400
        
        # Get document text
        document_text = project_repository.get_extracted_text(state.project_id) or ""
        
        entity_types_list = data.get('entity_types')
        parallel_profile_count = data.get('parallel_profile_count', 5)
        custom_agents_raw = data.get('custom_agents', [])
        # Run only on the user's custom agents (skip graph-derived population).
        # Defaults to False = merge custom agents into the auto-generated population.
        custom_agents_only = bool(data.get('custom_agents_only', False))
        # Simulation mode: 'policy' or 'product'. Drives persona framing + archetype
        # taxonomy. If the user explicitly chose a mode (touched the toggle/override)
        # `mode_is_manual` is True and that choice is pinned. Otherwise we auto-detect
        # from the seed (+ document) so users don't silently get the wrong mode.
        manual_mode = (data.get('mode') or '').strip().lower()
        if manual_mode not in ('policy', 'product'):
            manual_mode = ''
        mode_is_manual = bool(data.get('mode_is_manual')) and bool(manual_mode)

        # Keyword detection runs synchronously so the response can echo the banner
        # data immediately. The (optional) LLM tiebreak happens later in
        # prepare_simulation, where the LLM_* client is already constructed.
        detection = mode_detector.detect(simulation_requirement, document_text, llm_client=None)
        mode = manual_mode if mode_is_manual else detection["mode"]
        if mode not in ('policy', 'product'):
            mode = 'policy'

        # Parse custom agents if provided in request, else load from project
        custom_profiles = []
        if custom_agents_raw and len(custom_agents_raw) > 0:
            try:
                parser = CustomAgentParser()
                custom_profiles = parser.parse_raw(custom_agents_raw)
                logger.info(f"Received {len(custom_agents_raw)} raw custom agents from request, parsed {len(custom_profiles)} valid profiles")
            except Exception as e:
                logger.warning(f"Failed to parse custom agents from request: {e}")
        elif project.custom_agents and len(project.custom_agents) > 0:
            try:
                parser = CustomAgentParser()
                custom_profiles = parser.parse_raw(project.custom_agents)
                logger.info(f"Loaded {len(project.custom_agents)} custom agents from project, parsed {len(custom_profiles)} valid profiles")
            except Exception as e:
                logger.warning(f"Failed to parse custom agents from project: {e}")

        # Custom-only requested but nothing usable parsed — fail loudly rather than
        # silently falling back to a full auto-generated population the user didn't want.
        if custom_agents_only and len(custom_profiles) == 0:
            return jsonify({
                "success": False,
                "error": "Custom-agents-only mode is on, but no usable custom agents were provided. "
                         "Add at least one custom agent, or turn off custom-only mode."
            }), 400

        # ========== Get GraphStorage（Capture reference before background task starts） ==========
        storage = current_app.extensions.get('graph_storage')
        if not storage:
            raise ValueError("GraphStorage not initialized — check Neo4j connection")

        # ========== Synchronously get entity count（Before background task starts） ==========
        # This way frontend when callingprepareCan immediately getExpected total agents
        try:
            logger.info(f"Synchronously get entity count: graph_id={state.graph_id}")
            reader = EntityReader(storage)
            # Quickly read entities (no edge information, only statistics required)
            filtered_preview = reader.filter_defined_entities(
                graph_id=state.graph_id,
                defined_entity_types=entity_types_list,
                enrich_with_edges=False  # No edge information，Speed up
            )
            # The cast is drawn from the persona library, not these graph entities, so
            # the expected agent count is the library cast size — not filtered_count.
            # We still read entity_types here for display/context.
            from ..services.simulation_manager import DEFAULT_MAIN_CAST_SIZE
            state.entities_count = DEFAULT_MAIN_CAST_SIZE
            state.entity_types = list(filtered_preview.entity_types)
            logger.info(f"Graph entities (context only): {filtered_preview.filtered_count}, types: {filtered_preview.entity_types}")
        except Exception as e:
            logger.warning(f"Synchronously get entity countFailed（Will retry in background task）: {e}")
            # Failure does not affect subsequent process，Background task will retry
        
        # Create async task
        task_manager = TaskManager()
        task_id = task_manager.create_task(
            task_type="simulation_prepare",
            metadata={
                "simulation_id": simulation_id,
                "project_id": state.project_id
            }
        )
        
        # Update simulation status（Include pre-fetched entity count）
        state.status = SimulationStatus.PREPARING
        manager._save_simulation_state(state)
        
        # Define background task
        def run_prepare():
            try:
                task_manager.update_task(
                    task_id,
                    status=TaskStatus.PROCESSING,
                    progress=0,
                    message="Start preparing simulation environment..."
                )
                
                # PrepareSimulation（With progress callback）
                # Store stage progress details
                stage_details = {}
                
                def progress_callback(stage, progress, message, **kwargs):
                    # Calculate total progress
                    stage_weights = {
                        "reading": (0, 20),           # 0-20%
                        "generating_profiles": (20, 70),  # 20-70%
                        "generating_config": (70, 90),    # 70-90%
                        "copying_scripts": (90, 100)       # 90-100%
                    }
                    
                    start, end = stage_weights.get(stage, (0, 100))
                    current_progress = int(start + (end - start) * progress / 100)
                    
                    # Build detailed progress information
                    stage_names = {
                        "reading": "Read knowledge graph entities",
                        "generating_profiles": "GenerateAgentpersona",
                        "generating_config": "Generate simulation configuration",
                        "copying_scripts": "Prepare simulation scripts"
                    }
                    
                    stage_index = list(stage_weights.keys()).index(stage) + 1 if stage in stage_weights else 1
                    total_stages = len(stage_weights)
                    
                    # Update stage details
                    stage_details[stage] = {
                        "stage_name": stage_names.get(stage, stage),
                        "stage_progress": progress,
                        "current": kwargs.get("current", 0),
                        "total": kwargs.get("total", 0),
                        "item_name": kwargs.get("item_name", "")
                    }
                    
                    # Build detailed progress information
                    detail = stage_details[stage]
                    progress_detail_data = {
                        "current_stage": stage,
                        "current_stage_name": stage_names.get(stage, stage),
                        "stage_index": stage_index,
                        "total_stages": total_stages,
                        "stage_progress": progress,
                        "current_item": detail["current"],
                        "total_items": detail["total"],
                        "item_description": message
                    }
                    
                    # Build concise message
                    if detail["total"] > 0:
                        detailed_message = (
                            f"[{stage_index}/{total_stages}] {stage_names.get(stage, stage)}: "
                            f"{detail['current']}/{detail['total']} - {message}"
                        )
                    else:
                        detailed_message = f"[{stage_index}/{total_stages}] {stage_names.get(stage, stage)}: {message}"
                    
                    task_manager.update_task(
                        task_id,
                        progress=current_progress,
                        message=detailed_message,
                        progress_detail=progress_detail_data
                    )
                
                # Operator context: fetch the user's saved business description
                # (fail-open: empty string if Supabase not configured)
                try:
                    _uid = state.user_id or current_user_id()
                    _oc = oc_service.get(_uid) if _uid else ""
                except Exception:
                    _oc = ""

                result_state = manager.prepare_simulation(
                    simulation_id=simulation_id,
                    simulation_requirement=simulation_requirement,
                    document_text=document_text,
                    defined_entity_types=entity_types_list,
                    progress_callback=progress_callback,
                    parallel_profile_count=parallel_profile_count,
                    storage=storage,
                    custom_profiles=custom_profiles,
                    custom_only=custom_agents_only,
                    mode=mode,
                    detection=detection,
                    mode_is_manual=mode_is_manual,
                    operator_context=_oc,
                )

                # prepare_simulation returns a FAILED state (instead of raising)
                # for known issues like 0 matching entities. Surface that as a
                # failed task so the frontend stops polling and shows the error.
                if getattr(result_state, "status", None) == SimulationStatus.FAILED:
                    task_manager.fail_task(
                        task_id,
                        result_state.error or "Preparation failed"
                    )
                else:
                    task_manager.complete_task(
                        task_id,
                        result=result_state.to_simple_dict()
                    )
                
            except Exception as e:
                logger.error(f"Failed to prepare simulation: {str(e)}")
                task_manager.fail_task(task_id, str(e))
                
                # Update simulation status to failed
                state = manager.get_simulation(simulation_id)
                if state:
                    state.status = SimulationStatus.FAILED
                    state.error = str(e)
                    manager._save_simulation_state(state)
        
        # Start background thread
        thread = threading.Thread(target=run_prepare, daemon=True)
        thread.start()
        
        return jsonify({
            "success": True,
            "data": {
                "simulation_id": simulation_id,
                "task_id": task_id,
                "status": "preparing",
                "message": "Preparation task started，Please via /api/simulation/prepare/status Query progress",
                "already_prepared": False,
                "expected_entities_count": state.entities_count,  # Expected number of entities to process
                "entity_types": state.entity_types,  # Entity type list
                # Mode resolution — frontend renders the detection banner from this.
                # Note: the keyword decision is echoed here; an LLM tiebreak may still
                # refine the persisted mode during the async prepare task.
                "mode": mode,
                "mode_is_manual": mode_is_manual,
                "converged": detection["converged"],
                "secondary_lens": detection["secondary_lens"],
                "mode_detection": {
                    "decided_mode": detection["mode"],
                    "confidence": detection["confidence"],
                    "scores": detection["scores"],
                },
            }
        })
        
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 404
        
    except Exception as e:
        logger.error(f"Failed to start preparation task: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/prepare/status', methods=['POST'])
def get_prepare_status():
    """
    Query preparation task progress
    
    Support two query methods:
    1. Query via task_id to check ongoing task progress
    2. Check via simulation_id to verify if preparation is already completed
    
    Request (JSON):
        {
            "task_id": "task_xxxx",          // Optional, from previous /prepare call
            "simulation_id": "sim_xxxx"      // Optional，Simulation ID（For checking completedPrepare）
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "task_id": "task_xxxx",
                "status": "processing|completed|ready",
                "progress": 45,
                "message": "...",
                "already_prepared": true|false,  // Is there completed preparation
                "prepare_info": {...}            // Detailed information when preparation complete
            }
        }
    """
    from ..models.task import TaskManager
    
    try:
        data = request.get_json() or {}
        
        task_id = data.get('task_id')
        simulation_id = data.get('simulation_id')
        
        # If simulation_id is provided, check if preparation is complete
        if simulation_id:
            is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
            if is_prepared:
                return jsonify({
                    "success": True,
                    "data": {
                        "simulation_id": simulation_id,
                        "status": "ready",
                        "progress": 100,
                        "message": "Preparation already completed",
                        "already_prepared": True,
                        "prepare_info": prepare_info
                    }
                })
        
        # If no task_id，ReturnError
        if not task_id:
            if simulation_id:
                # Have simulation_idBut notPreparation complete
                return jsonify({
                    "success": True,
                    "data": {
                        "simulation_id": simulation_id,
                        "status": "not_started",
                        "progress": 0,
                        "message": "Preparation not started yet, please call /api/simulation/prepare",
                        "already_prepared": False
                    }
                })
            return jsonify({
                "success": False,
                "error": "Please provide task_id Or simulation_id"
            }), 400
        
        task_manager = TaskManager()
        task = task_manager.get_task(task_id)
        
        if not task:
            # Task does not exist, but if simulation_id is provided, check if preparation is complete
            if simulation_id:
                is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
                if is_prepared:
                    return jsonify({
                        "success": True,
                        "data": {
                            "simulation_id": simulation_id,
                            "task_id": task_id,
                            "status": "ready",
                            "progress": 100,
                            "message": "Task complete（PrepareWork already exists）",
                            "already_prepared": True,
                            "prepare_info": prepare_info
                        }
                    })
            
            return jsonify({
                "success": False,
                "error": f"Task does not exist: {task_id}"
            }), 404
        
        task_dict = task.to_dict()
        task_dict["already_prepared"] = False
        
        return jsonify({
            "success": True,
            "data": task_dict
        })
        
    except Exception as e:
        logger.error(f"Failed to query task status: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500


@simulation_bp.route('/<simulation_id>', methods=['DELETE'])
def delete_simulation(simulation_id: str):
    """Delete a simulation's data directory from disk.

    Refuses while the simulation is running. The id is validated against the
    directory's actual children so a crafted id can never escape the data dir.
    """
    try:
        import shutil

        if simulation_id in SimulationRunner.get_running_simulations():
            return jsonify({
                "success": False,
                "error": "Simulation is currently running — stop it before deleting."
            }), 409

        base_dir = os.path.abspath(Config.OASIS_SIMULATION_DATA_DIR)
        if simulation_id not in os.listdir(base_dir):
            return jsonify({"success": False, "error": f"Simulation {simulation_id} not found"}), 404

        target = os.path.join(base_dir, simulation_id)
        if not os.path.isdir(target):
            return jsonify({"success": False, "error": f"Simulation {simulation_id} not found"}), 404

        shutil.rmtree(target)
        logger.info(f"Deleted simulation {simulation_id} from disk")
        return jsonify({"success": True, "data": {"simulation_id": simulation_id}})

    except Exception as e:
        logger.error(f"Failed to delete simulation {simulation_id}: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/research/rerun', methods=['POST'])
def rerun_simulation_research(simulation_id: str):
    """Re-run deep web research for this simulation's archetypes.

    Reads entity types from the graph that this simulation is built on,
    runs the deep research pipeline, overwrites enrichment.json.
    
    Request body:
    {
        "agent_context": {
            "agents": [
                {
                    "name": "agent_name",
                    "archetype": "agent_archetype",
                    "description": "agent_description",
                    "background": "agent_background"
                }
            ],
            "context_focus": "specific_focus_area"
        }   // optional, custom agent context to shape research
    }
    """
    try:
        import re as _re
        from ..services.entity_reader import EntityReader
        from ..services.agent_enricher import AgentContextEnricher
        from ..services.deep_research_service import research_archetypes as _research

        manager = SimulationManager()
        state = manager._load_simulation_state(simulation_id)
        if not state:
            return jsonify({"success": False, "error": "Simulation not found"}), 404

        from ..storage import get_storage
        storage = get_storage()
        reader = EntityReader(storage)
        filtered = reader.filter_defined_entities(graph_id=state.graph_id, defined_entity_types=None, enrich_with_edges=False)

        def _norm(t):
            s = _re.sub(r'([A-Z])', r'_\1', t).lower().lstrip('_')
            return _re.sub(r'[\s\-]+', '_', s.strip())

        entity_types = list({_norm(e.type) for e in filtered.entities if e.type})
        if not entity_types:
            return jsonify({"success": False, "error": "No entity types found in graph"}), 400

        project = project_repository.get(state.project_id) if state.project_id else None
        seed = (project.simulation_requirement if project else "") or ""

        # Get agent context from request body
        agent_context = request.get_json() or {}

        raw_research = _research(
            archetypes=entity_types,
            query=seed or "current socio-economic conditions South Africa 2025",
            document_text=seed,
            agent_context=agent_context,
        )

        if not raw_research:
            return jsonify({
                "success": False,
                "error": "Research returned no results. Check FIRECRAWL_API_KEY and Firecrawl quota."
            }), 500

        enrichment = AgentContextEnricher.enrich_from_web_research(raw_research, entity_types)
        sim_dir = manager._get_simulation_dir(simulation_id)
        enrichment_file = os.path.join(sim_dir, "enrichment.json")
        with open(enrichment_file, 'w', encoding='utf-8') as f:
            json.dump(raw_research, f, ensure_ascii=False, indent=2)

        return jsonify({
            "success": True,
            "data": {
                "archetypes": entity_types,
                "enriched_count": len(enrichment),
                "enrichment": raw_research,
                "agent_context": agent_context,
            }
        })
    except Exception as e:
        logger.error(f"Re-run research failed for {simulation_id}: {e}")
        return jsonify({"success": False, "error": str(e), "traceback": traceback.format_exc()}), 500


# ============== Simulation execution control interface ==============

@simulation_bp.route('/start', methods=['POST'])
def start_simulation():
    """
    Start running simulation

    Request (JSON):
        {
            "simulation_id": "sim_xxxx",          // Required，Simulation ID
            "platform": "parallel",                // Optional: twitter / reddit / parallel (Default)
            "max_rounds": 100,                     // Optional: Maximum simulation rounds, default unlimited
            "enable_graph_memory_update": false,   // Optional: Whether to enable knowledge graph memory updates for agents
            "force": false                         // Optional: Force restart (stop running simulation and clean runtime files)
        }

    About force Parameters:
        - After enabling, if simulation is running or completed, clean runtime logs
        - Cleanup includes：run_state.json, actions.jsonl, simulation.log And so on
        - Will not clean configuration files（simulation_config.json）And profile File
        - For scenarios that need to rerun simulation

    About enable_graph_memory_update:
        - After enabling, all agents in the simulation will update the knowledge graph with their actions (posts, comments, follows, etc.)
        - This allows the knowledge graph to "remember" the simulation, improving context understanding and AI decision-making
        - Requires associated project to have valid graph_id
        - Uses batch update mechanism to reduce API overhead

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "runner_status": "running",
                "process_pid": 12345,
                "twitter_running": true,
                "reddit_running": true,
                "started_at": "2025-12-01T10:00:00",
                "graph_memory_update_enabled": true,  // Whether knowledge graph memory update enabled
                "force_restarted": true               // Whether is forced restart
            }
        }
    """
    try:
        data = request.get_json() or {}

        simulation_id = data.get('simulation_id')
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400

        platform = data.get('platform', 'opinion_space')
        max_rounds = data.get('max_rounds')  # Optional: Maximum simulation rounds
        enable_graph_memory_update = data.get('enable_graph_memory_update', False)  # Optional：IsFalseEnable knowledge graph memory update
        force = data.get('force', False)  # Optional：Force restart

        # New: Preset and simulation params
        preset = data.get('preset')  # 'quick', 'balanced', 'deep'
        # Free tier: force the smallest preset ('quick' = 6 rounds, ≤10 agents/round)
        # regardless of what was requested, to bound token spend on the trial sim.
        # Paid plans keep whatever they chose.
        ent = billing_service.get_entitlement(current_user_id())
        if ent.get('plan') != 'paid':
            preset = 'quick'
        convergence_threshold = data.get('convergence_threshold')
        convergence_window = data.get('convergence_window')
        max_agents_per_round = data.get('max_agents_per_round')
        min_agents_per_round = data.get('min_agents_per_round')

        # Verify max_rounds Parameters
        if max_rounds is not None:
            try:
                max_rounds = int(max_rounds)
                if max_rounds <= 0:
                    return jsonify({
                        "success": False,
                        "error": "max_rounds Must be positive integer"
                    }), 400
            except (ValueError, TypeError):
                return jsonify({
                    "success": False,
                    "error": "max_rounds Must be valid integer"
                }), 400

        if platform not in ['opinion_space']:
            return jsonify({
                "success": False,
                "error": f"Invalid platform type: {platform}. Only 'opinion_space' is supported."
            }), 400

        # Check if simulation is ready
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)

        if not state:
            return jsonify({
                "success": False,
                "error": f"Simulation does not exist: {simulation_id}"
            }), 404

        # The sim credit is charged here, once, on the first successful start
        # (guarded by the persisted credit_charged flag, so start→stop→start costs
        # one credit and a restart is never re-gated even after the trial runs
        # out). A sim created but never started charges nothing.
        if not state.credit_charged:
            gate = gates.sim_quota(current_user_id())
            if gate is not None:
                return gate

        force_restarted = False

        # A sim marked READY skips the whole preparedness block below, so nothing
        # ever confirmed its files were still on disk — the runner just tried to
        # open simulation_config.json and raised "Simulation config does not
        # exist, call /prepare endpoint first" at the user. That message is
        # internal (it names an endpoint they can't call) and it dead-ends: the
        # status stays READY, so every retry takes the same path and fails the
        # same way.
        #
        # The status is a claim about the files; verify the claim. If the files
        # are gone (a wiped/partially-restored sim dir, an ephemeral volume, a
        # prepare that set the status then lost its output), demote the status so
        # the pipeline's own probe reports "not prepared" and re-prepares instead
        # of looping.
        if state.status == SimulationStatus.READY:
            is_prepared, prepare_info = _check_simulation_prepared(simulation_id)
            if not is_prepared:
                logger.warning(
                    "Simulation %s claims READY but is not on disk (%s) — demoting to CREATED",
                    simulation_id, prepare_info.get("reason"),
                )
                state.status = SimulationStatus.CREATED
                state.config_generated = False
                manager._save_simulation_state(state)
                return jsonify({
                    "success": False,
                    "code": "needs_prepare",
                    "error": "This simulation's setup is missing, so it can't start. "
                             "Build it again — nothing was charged.",
                }), 409

        # Intelligently handle status: if preparation work is complete, reset status to ready
        if state.status != SimulationStatus.READY:
            # Check if preparation is complete
            is_prepared, prepare_info = _check_simulation_prepared(simulation_id)

            if is_prepared:
                # Preparation work complete, verify if simulation is not already running
                if state.status == SimulationStatus.RUNNING:
                    # Check if simulation process is really running
                    run_state = SimulationRunner.get_run_state(simulation_id)
                    if run_state and run_state.runner_status.value == "running":
                        # Process is indeed running
                        if force:
                            # Force mode：Stop runningSimulation
                            logger.info(f"Force mode：Stop runningSimulation {simulation_id}")
                            try:
                                SimulationRunner.stop_simulation(simulation_id)
                            except Exception as e:
                                logger.warning(f"Warning when stopping simulation: {str(e)}")
                        else:
                            return jsonify({
                                "success": False,
                                "error": f"Simulation is running. Please call /stop first or use force=true to force restart."
                            }), 400

                # If force mode，Clean runtime logs
                if force:
                    logger.info(f"Force mode: cleaning simulation runtime files for {simulation_id}")
                    cleanup_result = SimulationRunner.cleanup_simulation_logs(simulation_id)
                    if not cleanup_result.get("success"):
                        logger.warning(f"Warning when cleaning logs: {cleanup_result.get('errors')}")
                    force_restarted = True

                # Process does not exist or has ended，Reset status to ready
                logger.info(f"Simulation {simulation_id} preparation complete, resetting status to ready (previous status: {state.status.value})")
                state.status = SimulationStatus.READY
                manager._save_simulation_state(state)
            else:
                # Preparation not complete
                # Same reasoning as the READY check above: name the state in words
                # the person reading it can act on, and give the client a code it
                # can branch on rather than parsing prose.
                return jsonify({
                    "success": False,
                    "code": "needs_prepare",
                    "error": "This simulation hasn't finished being set up yet, so "
                             "it can't start. Build it again — nothing was charged.",
                }), 409
        
        # Get knowledge graphID（For knowledge graph memory update）
        graph_id = None
        if enable_graph_memory_update:
            # Get from simulation status or project graph_id
            graph_id = state.graph_id
            if not graph_id:
                # Try to get from project
                project = project_repository.get(state.project_id)
                if project:
                    graph_id = project.graph_id
            
            if not graph_id:
                return jsonify({
                    "success": False,
                    "error": "Enable knowledge graph memory update requires valid graph_id，Please ensure project graph built"
                }), 400
            
            logger.info(f"Enable knowledge graph memory update: simulation_id={simulation_id}, graph_id={graph_id}")
        
        # Load and update simulation config with preset params
        config_updated = False
        max_rounds_from_preset = None
        
        if preset or convergence_threshold or convergence_window or max_agents_per_round or min_agents_per_round:
            sim_dir = os.path.join(Config.OASIS_SIMULATION_DATA_DIR, simulation_id)
            config_path = os.path.join(sim_dir, "simulation_config.json")

            if os.path.exists(config_path):
                try:
                    with open(config_path, 'r', encoding='utf-8') as f:
                        config = json.load(f)

                    # Apply preset
                    if preset in SIM_PRESETS:
                        max_rounds_from_preset, time_overrides = apply_preset(config, preset)
                        logger.info(f"Applied preset '{preset}' to config: {simulation_id}, time_config={time_overrides}")

                    # Apply individual overrides
                    if convergence_threshold is not None:
                        config['convergence_threshold'] = float(convergence_threshold)
                    if convergence_window is not None:
                        config['convergence_window'] = int(convergence_window)
                    if max_agents_per_round is not None:
                        config['max_agents_per_round'] = int(max_agents_per_round)
                    if min_agents_per_round is not None:
                        config['min_agents_per_round'] = int(min_agents_per_round)

                    with open(config_path, 'w', encoding='utf-8') as f:
                        json.dump(config, f, ensure_ascii=False, indent=2)
                    config_updated = True
                except Exception as e:
                    logger.warning(f"Failed to update config with preset params: {e}")

        # Use max_rounds from preset if not explicitly set
        if max_rounds is None and max_rounds_from_preset is not None:
            max_rounds = max_rounds_from_preset
            logger.info(f"Using max_rounds={max_rounds} from preset")

        # Start simulation
        run_state = SimulationRunner.start_simulation(
            simulation_id=simulation_id,
            platform=platform,
            max_rounds=max_rounds,
            enable_graph_memory_update=enable_graph_memory_update,
            graph_id=graph_id
        )

        # Charge the sim credit now that the run actually started. Guarded by the
        # persisted credit_charged flag so a stopped + restarted sim never pays
        # twice (and recharging is skipped on restart even after the trial runs
        # out). The flag survives Railway restarts because it is saved with state.
        if not state.credit_charged:
            billing_service.increment_sim_used(current_user_id())
            state.credit_charged = True

        # Update simulation status
        state.status = SimulationStatus.RUNNING
        manager._save_simulation_state(state)
        
        response_data = run_state.to_dict()
        if max_rounds:
            response_data['max_rounds_applied'] = max_rounds
        response_data['graph_memory_update_enabled'] = enable_graph_memory_update
        response_data['force_restarted'] = force_restarted
        if enable_graph_memory_update:
            response_data['graph_id'] = graph_id
        
        return jsonify({
            "success": True,
            "data": response_data
        })
        
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
        
    except Exception as e:
        logger.error(f"Failed to start simulation: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/stop', methods=['POST'])
def stop_simulation():
    """
    Stop simulation
    
    Request (JSON):
        {
            "simulation_id": "sim_xxxx"  // Required，Simulation ID
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "runner_status": "stopped",
                "completed_at": "2025-12-01T12:00:00"
            }
        }
    """
    try:
        data = request.get_json() or {}
        
        simulation_id = data.get('simulation_id')
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400
        
        run_state = SimulationRunner.stop_simulation(simulation_id)
        
        # Update simulation status
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)
        if state:
            state.status = SimulationStatus.PAUSED
            manager._save_simulation_state(state)
        
        return jsonify({
            "success": True,
            "data": run_state.to_dict()
        })
        
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
        
    except Exception as e:
        logger.error(f"Failed to stop simulation: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


# ============== Interview Interview interface ==============


@simulation_bp.route('/env-status', methods=['POST'])
def get_env_status():
    """
    Get simulation environment status

    Check if simulation environment is alive (can receive interview requests).

    Request (JSON):
        {
            "simulation_id": "sim_xxxx"  // Required，Simulation ID
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "env_alive": true,
                "twitter_available": true,
                "reddit_available": true,
                "message": "Environment running, ready to receive interview requests"
            }
        }
    """
    try:
        data = request.get_json() or {}
        
        simulation_id = data.get('simulation_id')
        
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400

        env_alive = SimulationRunner.check_env_alive(simulation_id)
        
        # Get more detailed status information
        env_status = SimulationRunner.get_env_status_detail(simulation_id)

        if env_alive:
            message = "Environment running, ready to receive interview requests"
        else:
            message = "Environment not running or closed"

        return jsonify({
            "success": True,
            "data": {
                "simulation_id": simulation_id,
                "env_alive": env_alive,
                "twitter_available": env_status.get("twitter_available", False),
                "reddit_available": env_status.get("reddit_available", False),
                "message": message
            }
        })

    except Exception as e:
        logger.error(f"Failed to get environment status: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/close-env', methods=['POST'])
def close_simulation_env():
    """
    Close simulation environment
    
    Send close environment command to simulation to gracefully exit and wait for completion.

    Note: This is different from /stop. /stop terminates the simulation abruptly.
    This interface lets the simulation gracefully close the environment and exit.
    
    Request (JSON):
        {
            "simulation_id": "sim_xxxx",  // Required，Simulation ID
            "timeout": 30                  // Optional, timeout in seconds, default 30
        }
    
    Returns:
        {
            "success": true,
            "data": {
                "message": "Environment close command sent",
                "result": {...},
                "timestamp": "2025-12-08T10:00:01"
            }
        }
    """
    try:
        data = request.get_json() or {}
        
        simulation_id = data.get('simulation_id')
        timeout = data.get('timeout', 30)
        
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400
        
        result = SimulationRunner.close_simulation_env(
            simulation_id=simulation_id,
            timeout=timeout
        )
        
        # Update simulation status
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)
        if state:
            state.status = SimulationStatus.COMPLETED
            manager._save_simulation_state(state)
        
        return jsonify({
            "success": result.get("success", False),
            "data": result
        })
        
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
        
    except Exception as e:
        logger.error(f"Failed to close environment: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


# =============================================================================
# Policy Wind Tunnel — Interview & Intervention APIs
# =============================================================================


@simulation_bp.route('/<simulation_id>/agents/<int:agent_id>/interview', methods=['POST'])
def interview_single_agent(simulation_id: str, agent_id: int):
    """
    Interview a single agent (post-hoc, no running simulation required).

    Request (JSON):
        {
            "question": "What is your honest first reaction?",  // Required if question_type not set
            "question_type": "first_reaction",                 // Optional: structured question type
            "policy_context": "Fuel levy increase of 75c/L"     // Optional: for structured questions
        }

    Supported question_type values:
        - "first_reaction": What is your honest first reaction?
        - "what_would_work": What would make this work for you?
        - "what_puts_you_off": What, if anything, would put you off?
        - "need_to_know": What would you need to know before deciding?
        - "who_you_would_tell": Would you tell anyone about it?

    Returns:
        {
            "success": true,
            "data": {
                "agent_id": 5,
                "agent_name": "Taxi Association Chair",
                "response": "Our biggest concern is...",
                "stance_before": "oppose",
                "stance_after": "concerned",
                "stance_changed": true,
                "actor_archetype": "community_protector",
                "timestamp": "2026-05-05T10:00:00"
            }
        }
    """
    try:
        data = request.get_json() or {}
        question = data.get('question', '')
        question_type = data.get('question_type')
        policy_context = data.get('policy_context')

        if not question and not question_type:
            return jsonify({
                "success": False,
                "error": "Provide 'question' or 'question_type'"
            }), 400

        service = InterviewService(simulation_id)

        # Run async interview in sync Flask context
        loop = asyncio.new_event_loop()
        try:
            result = loop.run_until_complete(service.interview_agent(
                agent_id=agent_id,
                question=question,
                question_type=question_type,
                policy_context=policy_context,
            ))
        finally:
            loop.close()

        return jsonify({
            "success": True,
            "data": result
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 404
    except Exception as e:
        logger.error(f"Interview failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/agents/batch-interview', methods=['POST'])
def batch_interview_agents(simulation_id: str):
    """
    Interview multiple agents with the same question.

    Request (JSON):
        {
            "question": "What is your biggest concern?",
            "question_type": "first_reaction",         // Optional
            "policy_context": "Fuel levy increase...", // Optional
            "agent_ids": [5, 12, 23]                   // Optional (default: all agents)
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "total_interviewed": 50,
                "successful": 48,
                "failed": 2,
                "stance_distribution": {"oppose": 20, "concerned": 15, ...},
                "results": [...]
            }
        }
    """
    try:
        data = request.get_json() or {}
        question = data.get('question', '')
        question_type = data.get('question_type')
        policy_context = data.get('policy_context')
        agent_ids = data.get('agent_ids')

        if not question and not question_type:
            return jsonify({
                "success": False,
                "error": "Provide 'question' or 'question_type'"
            }), 400

        service = InterviewService(simulation_id)

        loop = asyncio.new_event_loop()
        try:
            result = loop.run_until_complete(service.batch_interview(
                question=question,
                agent_ids=agent_ids,
                question_type=question_type,
                policy_context=policy_context,
            ))
        finally:
            loop.close()

        return jsonify({
            "success": True,
            "data": result
        })

    except Exception as e:
        logger.error(f"Batch interview failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/agents/<int:agent_id>/intervene', methods=['POST'])
def intervene_with_agent(simulation_id: str, agent_id: int):
    """
    Apply a policy-maker intervention to an agent.

    Request (JSON):
        {
            "intervention_text": "We will offer a R500/month taxi operator subsidy"
        }

    Returns:
        {
            "success": true,
            "data": {
                "agent_id": 5,
                "agent_name": "Taxi Association Chair",
                "response": "That changes things...",
                "stance_before": "oppose",
                "stance_after": "concerned",
                "radicalism_before": 4,
                "radicalism_after": 2,
                "mobilization_before": 2,
                "mobilization_after": 1,
                "stance_changed": true,
                "timestamp": "2026-05-05T10:00:00"
            }
        }
    """
    try:
        data = request.get_json() or {}
        intervention_text = data.get('intervention_text')

        if not intervention_text:
            return jsonify({
                "success": False,
                "error": "Provide 'intervention_text'"
            }), 400

        service = InterviewService(simulation_id)

        loop = asyncio.new_event_loop()
        try:
            result = loop.run_until_complete(service.intervene_with_agent(
                agent_id=agent_id,
                intervention_text=intervention_text,
            ))
        finally:
            loop.close()

        return jsonify({
            "success": True,
            "data": result
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 404
    except Exception as e:
        logger.error(f"Intervention failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/fork', methods=['POST'])
def fork_simulation(simulation_id: str):
    """
    Fork a simulation, optionally modifying agent states.

    Request (JSON):
        {
            "new_simulation_id": "sim_xxxx_fork1",
            "agent_modifications": {
                "5": {"stance": "support", "current_radicalism": 2},
                "12": {"stance": "neutral", "current_radicalism": 1}
            }
        }

    Returns:
        {
            "success": true,
            "data": {
                "original_simulation_id": "sim_xxxx",
                "new_simulation_id": "sim_xxxx_fork1",
                "new_simulation_dir": "/path/to/sim",
                "modified_agents": 2
            }
        }
    """
    try:
        data = request.get_json() or {}
        new_simulation_id = data.get('new_simulation_id')
        agent_modifications_raw = data.get('agent_modifications', {})

        if not new_simulation_id:
            return jsonify({
                "success": False,
                "error": "Provide 'new_simulation_id'"
            }), 400

        # Convert string keys to int keys (JSON keys are strings)
        agent_modifications = {}
        for k, v in agent_modifications_raw.items():
            try:
                agent_modifications[int(k)] = v
            except ValueError:
                continue

        service = InterviewService(simulation_id)
        new_dir = service.fork_simulation(new_simulation_id, agent_modifications)

        return jsonify({
            "success": True,
            "data": {
                "original_simulation_id": simulation_id,
                "new_simulation_id": new_simulation_id,
                "new_simulation_dir": new_dir,
                "modified_agents": len(agent_modifications),
            }
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
    except Exception as e:
        logger.error(f"Fork failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


# =============================================================================
# In-Simulation Pause & Intervention APIs
# =============================================================================

@simulation_bp.route('/<simulation_id>/pause', methods=['POST'])
def pause_simulation(simulation_id: str):
    """
    Pause a running simulation between rounds.

    The simulation will complete the current round, then pause before
    starting the next round. While paused, you can interview agents
    and apply interventions.

    Returns:
        {
            "success": true,
            "data": {
                "paused": true,
                "message": "Simulation paused"
            }
        }
    """
    try:
        result = SimulationRunner.pause_simulation(simulation_id)
        return jsonify({
            "success": result.get("success", False),
            "data": result
        })
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
    except Exception as e:
        logger.error(f"Pause failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/resume', methods=['POST'])
def resume_simulation(simulation_id: str):
    """
    Resume a paused simulation.

    Returns:
        {
            "success": true,
            "data": {
                "paused": false,
                "message": "Simulation resumed"
            }
        }
    """
    try:
        result = SimulationRunner.resume_simulation(simulation_id)
        return jsonify({
            "success": result.get("success", False),
            "data": result
        })
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
    except Exception as e:
        logger.error(f"Resume failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/agents/<int:agent_id>/intervene-live', methods=['POST'])
def intervene_live(simulation_id: str, agent_id: int):
    """
    Apply an intervention to an agent during a running (paused) simulation.

    Request (JSON):
        {
            "intervention_text": "We will offer a R500/month taxi operator subsidy"
        }

    Returns:
        {
            "success": true,
            "data": {
                "agent_id": 5,
                "response": "That changes things...",
                "stance_before": "oppose",
                "stance_after": "concerned",
                "radicalism_before": 4,
                "radicalism_after": 2,
                "mobilization_before": 2,
                "mobilization_after": 1,
                "propagation_count": 3,
                "stance_changed": true
            }
        }
    """
    try:
        data = request.get_json() or {}
        intervention_text = data.get('intervention_text')

        if not intervention_text:
            return jsonify({
                "success": False,
                "error": "Provide 'intervention_text'"
            }), 400

        result = SimulationRunner.apply_intervention_during_sim(
            simulation_id=simulation_id,
            agent_id=agent_id,
            intervention_text=intervention_text,
        )

        # No judge on the live-intervention path: it's interactive and judging it
        # would add a blocking Plus-tier call per poke while gating nothing.
        response_data = result.get("result") or result

        return jsonify({
            "success": result.get("success", False),
            "data": response_data
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
    except Exception as e:
        logger.error(f"Live intervention failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


@simulation_bp.route('/<simulation_id>/broadcast-intervention', methods=['POST'])
def broadcast_intervention(simulation_id: str):
    """
    Broadcast a founder announcement into the opinion space during a running
    (paused) simulation. The message posts to the feed and the whole active
    room reacts next round — unlike intervene-live, which targets one agent.

    Request (JSON):
        {
            "intervention_text": "We just made it free for the first 3 months",
            "founder_name": "Nkosinathi Themba"   # optional
        }
    """
    try:
        data = request.get_json() or {}
        intervention_text = data.get('intervention_text')
        founder_name = data.get('founder_name') or ""

        if not intervention_text:
            return jsonify({
                "success": False,
                "error": "Provide 'intervention_text'"
            }), 400

        result = SimulationRunner.broadcast_intervention_during_sim(
            simulation_id=simulation_id,
            intervention_text=intervention_text,
            founder_name=founder_name,
        )

        # No judge on the broadcast path: interactive, and a blocking Plus-tier
        # call per broadcast gates nothing.
        response_data = result.get("result") or result

        return jsonify({
            "success": result.get("success", False),
            "data": response_data
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
    except Exception as e:
        logger.error(f"Broadcast intervention failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


# ============== Impact-Extraction Interview API ==============

@simulation_bp.route('/interview/impact', methods=['POST'])
def impact_interview():
    """
    Batch impact-extraction interview with auto-reframing per agent.

    The system analyzes the user's generic question, reframes it per agent persona,
    interviews all agents, and returns structured impact metadata.

    Request (JSON):
        {
            "simulation_id": "sim_xxxx",   // Required
            "question": "What if the policy changes after 12 months?",  // Required
            "agent_ids": [1, 4, 7]         // Optional, default all agents
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "original_question": "What if the policy changes after 12 months?",
                "question_archetype": "counterfactual",
                "total_interviewed": 8,
                "impact_dashboard": {
                    "emotional_temperature": {"fear": 5, "anger": 2, "sadness": 1},
                    "stance_distribution": {"support": 3, "concerned": 4, "oppose": 1},
                    "mobilization_risk": {"low": 5, "medium": 2, "high": 1},
                    "predicted_actions": [...]
                },
                "results": [
                    {
                        "agent_id": 1,
                        "agent_name": "Agent Name",
                        "response": "The changes will affect my community...",
                        "reframed_question": "The policy change happens next month...",
                        "impact_metadata": {
                            "granularity": "micro",
                            "affected_entity": "Family",
                            "emotional_tone": "fear",
                            "predicted_action": "keep son indoors"
                        },
                        "internal_state": {
                            "emotion": {"fear": 9, "anger": 2, ...},
                            "needs": {"safety_physical": 95, ...},
                            "stance": "support"
                        }
                    }
                ]
            }
        }
    """
    try:
        data = request.get_json() or {}
        simulation_id = data.get("simulation_id")
        question = data.get("question", "")
        agent_ids = data.get("agent_ids")

        if not simulation_id:
            return jsonify({"success": False, "error": "simulation_id is required"}), 400
        if not question:
            return jsonify({"success": False, "error": "question is required"}), 400

        service = InterviewService(simulation_id)

        # Run batch impact interview (async)
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            result = loop.run_until_complete(
                service.batch_impact_interview(
                    question=question,
                    agent_ids=agent_ids,
                )
            )
        finally:
            loop.close()

        return jsonify({
            "success": True,
            "data": result
        })

    except Exception as e:
        logger.error(f"Impact interview failed: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


