"""
Simulation-related API routes
Step2: Entity reading and filtering, OASIS simulation preparation and execution (fully automated)
"""

import os
import json
import traceback
from typing import Optional
from flask import request, jsonify

from . import simulation_bp
from ..auth import current_user_id
from ..controllers import gates
from ..services import billing_service
from ..config import Config
from ..services.simulation_manager import SimulationManager, SimulationStatus
from ..services.simulation_runner import SimulationRunner
from ..services import simulation_setup_service
from ..services.sim_presets import SIM_PRESETS, apply_preset
from ..utils.logger import get_logger
from ..repositories import project_repository

logger = get_logger('fub.api.simulation')


# ============== Simulation management interface ==============

@simulation_bp.route('/create', methods=['POST'])
def create_simulation():
    """
    Create new simulation
    
    Note: parameters like max_rounds are intelligently generated by LLM, no manual setting needed
    
    Request (JSON):
        {
            "project_id": "proj_xxxx",  // Required
            "graph_id": "fub_xxxx"      // Optional, if not provided, get from project
        }

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "project_id": "proj_xxxx",
                "graph_id": "fub_xxxx",
                "status": "created",
                "created_at": "2025-12-01T10:00:00"
            }
        }
    """
    # Simulations are paid, with a free trial (FREE_SIM_LIMIT) for closed-beta
    # testing while Paystack approval is pending. The quota is checked here so a
    # user is told up front they are out of runs; the credit itself is charged
    # only when the run actually starts (see /start), so a sim that is created
    # but never started costs nothing.
    gate = gates.sim_quota(current_user_id())
    if gate is not None:
        return gate
    try:
        data = request.get_json() or {}

        project_id = data.get('project_id')
        if not project_id:
            return jsonify({
                "success": False,
                "error": "Please provide project_id"
            }), 400
        
        project = project_repository.get(project_id)
        if not project:
            return jsonify({
                "success": False,
                "error": f"Project does not exist: {project_id}"
            }), 404
        
        graph_id = data.get('graph_id') or project.graph_id
        if not graph_id:
            return jsonify({
                "success": False,
                "error": "Project has not built knowledge graph yet, please call /api/graph/build first"
            }), 400
        
        manager = SimulationManager()
        state = manager.create_simulation(
            project_id=project_id,
            graph_id=graph_id,
            user_id=current_user_id(),
        )

        # No charge here — the sim credit is taken at /start, once the run
        # actually begins (see start_simulation).
        return jsonify({
            "success": True,
            "data": state.to_dict()
        })
        
    except Exception as e:
        logger.error(f"Failed to create simulation: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


# ============== Simulation execution control interface ==============

@simulation_bp.route('/start', methods=['POST'])
def start_simulation():
    """
    Start running simulation

    Request (JSON):
        {
            "simulation_id": "sim_xxxx",          // Required，Simulation ID
            "platform": "parallel",                // Optional: twitter / reddit / parallel (Default)
            "max_rounds": 100,                     // Optional: Maximum simulation rounds, default unlimited
            "enable_graph_memory_update": false,   // Optional: Whether to enable knowledge graph memory updates for agents
            "force": false                         // Optional: Force restart (stop running simulation and clean runtime files)
        }

    About force Parameters:
        - After enabling, if simulation is running or completed, clean runtime logs
        - Cleanup includes：run_state.json, actions.jsonl, simulation.log And so on
        - Will not clean configuration files（simulation_config.json）And profile File
        - For scenarios that need to rerun simulation

    About enable_graph_memory_update:
        - After enabling, all agents in the simulation will update the knowledge graph with their actions (posts, comments, follows, etc.)
        - This allows the knowledge graph to "remember" the simulation, improving context understanding and AI decision-making
        - Requires associated project to have valid graph_id
        - Uses batch update mechanism to reduce API overhead

    Returns:
        {
            "success": true,
            "data": {
                "simulation_id": "sim_xxxx",
                "runner_status": "running",
                "process_pid": 12345,
                "twitter_running": true,
                "reddit_running": true,
                "started_at": "2025-12-01T10:00:00",
                "graph_memory_update_enabled": true,  // Whether knowledge graph memory update enabled
                "force_restarted": true               // Whether is forced restart
            }
        }
    """
    try:
        data = request.get_json() or {}

        simulation_id = data.get('simulation_id')
        if not simulation_id:
            return jsonify({
                "success": False,
                "error": "Please provide simulation_id"
            }), 400

        platform = data.get('platform', 'opinion_space')
        max_rounds = data.get('max_rounds')  # Optional: Maximum simulation rounds
        enable_graph_memory_update = data.get('enable_graph_memory_update', False)  # Optional：IsFalseEnable knowledge graph memory update
        force = data.get('force', False)  # Optional：Force restart

        # New: Preset and simulation params
        preset = data.get('preset')  # 'quick', 'balanced', 'deep'
        # Free tier: force the smallest preset ('quick' = 6 rounds, ≤10 agents/round)
        # regardless of what was requested, to bound token spend on the trial sim.
        # Paid plans keep whatever they chose.
        ent = billing_service.get_entitlement(current_user_id())
        if ent.get('plan') != 'paid':
            preset = 'quick'
        convergence_threshold = data.get('convergence_threshold')
        convergence_window = data.get('convergence_window')
        max_agents_per_round = data.get('max_agents_per_round')
        min_agents_per_round = data.get('min_agents_per_round')

        # Verify max_rounds Parameters
        if max_rounds is not None:
            try:
                max_rounds = int(max_rounds)
                if max_rounds <= 0:
                    return jsonify({
                        "success": False,
                        "error": "max_rounds Must be positive integer"
                    }), 400
            except (ValueError, TypeError):
                return jsonify({
                    "success": False,
                    "error": "max_rounds Must be valid integer"
                }), 400

        if platform not in ['opinion_space']:
            return jsonify({
                "success": False,
                "error": f"Invalid platform type: {platform}. Only 'opinion_space' is supported."
            }), 400

        # Check if simulation is ready
        manager = SimulationManager()
        state = manager.get_simulation(simulation_id)

        if not state:
            return jsonify({
                "success": False,
                "error": f"Simulation does not exist: {simulation_id}"
            }), 404

        # The sim credit is charged here, once, on the first successful start
        # (guarded by the persisted credit_charged flag, so start→stop→start costs
        # one credit and a restart is never re-gated even after the trial runs
        # out). A sim created but never started charges nothing.
        if not state.credit_charged:
            gate = gates.sim_quota(current_user_id())
            if gate is not None:
                return gate

        force_restarted = False

        # A sim marked READY skips the whole preparedness block below, so nothing
        # ever confirmed its files were still on disk — the runner just tried to
        # open simulation_config.json and raised "Simulation config does not
        # exist, call /prepare endpoint first" at the user. That message is
        # internal (it names an endpoint they can't call) and it dead-ends: the
        # status stays READY, so every retry takes the same path and fails the
        # same way.
        #
        # The status is a claim about the files; verify the claim. If the files
        # are gone (a wiped/partially-restored sim dir, an ephemeral volume, a
        # prepare that set the status then lost its output), demote the status so
        # the pipeline's own probe reports "not prepared" and re-prepares instead
        # of looping.
        if state.status == SimulationStatus.READY:
            is_prepared, prepare_info = simulation_setup_service.check_prepared(simulation_id)
            if not is_prepared:
                logger.warning(
                    "Simulation %s claims READY but is not on disk (%s) — demoting to CREATED",
                    simulation_id, prepare_info.get("reason"),
                )
                state.status = SimulationStatus.CREATED
                state.config_generated = False
                manager._save_simulation_state(state)
                return jsonify({
                    "success": False,
                    "code": "needs_prepare",
                    "error": "This simulation's setup is missing, so it can't start. "
                             "Build it again — nothing was charged.",
                }), 409

        # Intelligently handle status: if preparation work is complete, reset status to ready
        if state.status != SimulationStatus.READY:
            # Check if preparation is complete
            is_prepared, prepare_info = simulation_setup_service.check_prepared(simulation_id)

            if is_prepared:
                # Preparation work complete, verify if simulation is not already running
                if state.status == SimulationStatus.RUNNING:
                    # Check if simulation process is really running
                    run_state = SimulationRunner.get_run_state(simulation_id)
                    if run_state and run_state.runner_status.value == "running":
                        # Process is indeed running
                        if force:
                            # Force mode：Stop runningSimulation
                            logger.info(f"Force mode：Stop runningSimulation {simulation_id}")
                            try:
                                SimulationRunner.stop_simulation(simulation_id)
                            except Exception as e:
                                logger.warning(f"Warning when stopping simulation: {str(e)}")
                        else:
                            return jsonify({
                                "success": False,
                                "error": f"Simulation is running. Please call /stop first or use force=true to force restart."
                            }), 400

                # If force mode，Clean runtime logs
                if force:
                    logger.info(f"Force mode: cleaning simulation runtime files for {simulation_id}")
                    cleanup_result = SimulationRunner.cleanup_simulation_logs(simulation_id)
                    if not cleanup_result.get("success"):
                        logger.warning(f"Warning when cleaning logs: {cleanup_result.get('errors')}")
                    force_restarted = True

                # Process does not exist or has ended，Reset status to ready
                logger.info(f"Simulation {simulation_id} preparation complete, resetting status to ready (previous status: {state.status.value})")
                state.status = SimulationStatus.READY
                manager._save_simulation_state(state)
            else:
                # Preparation not complete
                # Same reasoning as the READY check above: name the state in words
                # the person reading it can act on, and give the client a code it
                # can branch on rather than parsing prose.
                return jsonify({
                    "success": False,
                    "code": "needs_prepare",
                    "error": "This simulation hasn't finished being set up yet, so "
                             "it can't start. Build it again — nothing was charged.",
                }), 409
        
        # Get knowledge graphID（For knowledge graph memory update）
        graph_id = None
        if enable_graph_memory_update:
            # Get from simulation status or project graph_id
            graph_id = state.graph_id
            if not graph_id:
                # Try to get from project
                project = project_repository.get(state.project_id)
                if project:
                    graph_id = project.graph_id
            
            if not graph_id:
                return jsonify({
                    "success": False,
                    "error": "Enable knowledge graph memory update requires valid graph_id，Please ensure project graph built"
                }), 400
            
            logger.info(f"Enable knowledge graph memory update: simulation_id={simulation_id}, graph_id={graph_id}")
        
        # Load and update simulation config with preset params
        config_updated = False
        max_rounds_from_preset = None
        
        if preset or convergence_threshold or convergence_window or max_agents_per_round or min_agents_per_round:
            sim_dir = os.path.join(Config.OASIS_SIMULATION_DATA_DIR, simulation_id)
            config_path = os.path.join(sim_dir, "simulation_config.json")

            if os.path.exists(config_path):
                try:
                    with open(config_path, 'r', encoding='utf-8') as f:
                        config = json.load(f)

                    # Apply preset
                    if preset in SIM_PRESETS:
                        max_rounds_from_preset, time_overrides = apply_preset(config, preset)
                        logger.info(f"Applied preset '{preset}' to config: {simulation_id}, time_config={time_overrides}")

                    # Apply individual overrides
                    if convergence_threshold is not None:
                        config['convergence_threshold'] = float(convergence_threshold)
                    if convergence_window is not None:
                        config['convergence_window'] = int(convergence_window)
                    if max_agents_per_round is not None:
                        config['max_agents_per_round'] = int(max_agents_per_round)
                    if min_agents_per_round is not None:
                        config['min_agents_per_round'] = int(min_agents_per_round)

                    with open(config_path, 'w', encoding='utf-8') as f:
                        json.dump(config, f, ensure_ascii=False, indent=2)
                    config_updated = True
                except Exception as e:
                    logger.warning(f"Failed to update config with preset params: {e}")

        # Use max_rounds from preset if not explicitly set
        if max_rounds is None and max_rounds_from_preset is not None:
            max_rounds = max_rounds_from_preset
            logger.info(f"Using max_rounds={max_rounds} from preset")

        # Start simulation
        run_state = SimulationRunner.start_simulation(
            simulation_id=simulation_id,
            platform=platform,
            max_rounds=max_rounds,
            enable_graph_memory_update=enable_graph_memory_update,
            graph_id=graph_id
        )

        # Charge the sim credit now that the run actually started. Guarded by the
        # persisted credit_charged flag so a stopped + restarted sim never pays
        # twice (and recharging is skipped on restart even after the trial runs
        # out). The flag survives Railway restarts because it is saved with state.
        if not state.credit_charged:
            billing_service.increment_sim_used(current_user_id())
            state.credit_charged = True

        # Update simulation status
        state.status = SimulationStatus.RUNNING
        manager._save_simulation_state(state)
        
        response_data = run_state.to_dict()
        if max_rounds:
            response_data['max_rounds_applied'] = max_rounds
        response_data['graph_memory_update_enabled'] = enable_graph_memory_update
        response_data['force_restarted'] = force_restarted
        if enable_graph_memory_update:
            response_data['graph_id'] = graph_id
        
        return jsonify({
            "success": True,
            "data": response_data
        })
        
    except ValueError as e:
        return jsonify({
            "success": False,
            "error": str(e)
        }), 400
        
    except Exception as e:
        logger.error(f"Failed to start simulation: {str(e)}")
        return jsonify({
            "success": False,
            "error": str(e),
            "traceback": traceback.format_exc()
        }), 500


